import { useDraggable } from '@dnd-kit/core'
import { CSS } from '@dnd-kit/utilities'
import { useEffect, useRef, useState } from 'react'
import { TextInput } from '@components/inputs'
import { UserRoles } from '@constants'
import { FieldsTypeEnum } from '@components/Esign/components/SidebarData'
import { RubberBand } from '@components/Esign'
import SignatureCanvas from 'react-signature-canvas'
import { Button } from '@components/buttons'

export const LogbookDraggableTabUpdated = ({
    item,
    onResize,
    onResized,
    onItemSelected,
    onRemove,
    tabsError,
    viewport,
}: any) => {
    const { attributes, listeners, setNodeRef, transform }: any = useDraggable({
        id: `input-tab-${item.id}`,
        data: { ...item, dataLabel: 'autogenerated-datalabel', viewport },
    })
    const buttonRef = useRef<any>(null)

    const handleClick = (e: any) => {
        e.stopPropagation()
    }

    const ref = useRef<any>(null)

    const [isTabError, setIsTabError] = useState(false)

    useEffect(() => {
        if (
            tabsError &&
            tabsError?.map((tab: any) => tab.id).includes(item?.id)
        ) {
            setIsTabError(true)
        }
        if (item?.data?.role) {
            setIsTabError(false)
        }
    }, [item?.data?.role, tabsError])

    const style = {
        ...(transform
            ? {
                  transform: CSS.Translate.toString({
                      x: transform.x + item.location?.x,
                      y: transform.y + item.location?.y,
                      scaleX: transform?.scaleX,
                      scaleY: transform?.scaleY,
                  }),
              }
            : {}),
    }

    return (
        <g
            id={item?.id}
            data-view-name="tab"
            data-view-id=""
            cursor={'grab'}
            ref={setNodeRef}
            className="outline-none z-50"
            {...(item.moving
                ? { style: { ...style } }
                : {
                      transform: `matrix(1 0 0 1 ${item.location.x} ${item.location.y})`,
                  })}
            onMouseDown={(e: any) => {
                e?.stopPropagation()
                onItemSelected(item, !item.selected, true)
            }}
            {...listeners}
            onKeyDown={(e: any) => {
                e.stopPropagation()
                var key = e.which || e.keyCode || e.charCode
                if (key == 8 || key == 46) {
                    onRemove(item)
                }

                listeners.onKeyDown(e)
            }}
            {...attributes}
        >
            {item?.data?.type === FieldsTypeEnum.Checkbox ? (
                <>
                    <rect
                        x="0"
                        y="0"
                        width="11"
                        height="11"
                        fill={
                            !item?.data?.role && isTabError
                                ? 'red'
                                : item.data?.color
                        }
                        stroke="black"
                        strokeWidth="1"
                        // onClick={handleCheckboxChange}
                    />
                    <text x="2" y="9" className="text-[9px]" fill={'white'}>
                        ✔
                    </text>
                </>
            ) : (
                <>
                    {!item?.data?.role && isTabError ? (
                        <>
                            <rect
                                x="0" // Adjust the x-coordinate to move the background closer to the text
                                y="-9" // Adjust the y-coordinate to move the background closer to the text
                                width={item.size?.width} // Adjust the width to reduce the size of the background
                                height="8" // Adjust the height to reduce the size of the background
                                fill="white" // Replace 'yellow' with the desired background color
                                fillOpacity="1"
                            />
                            <text
                                x="2"
                                y="-2"
                                className="text-[7px] "
                                fill={'red'}
                            >
                                Please Select the role
                            </text>
                        </>
                    ) : (
                        item?.data?.isCustom && (
                            <text
                                style={{
                                    backgroundColor: 'yellow',
                                    fontSize: '7px',
                                    color: item.data?.color,
                                }}
                                className="uppercase"
                                x="2"
                                y="-2"
                                // fill={item.data?.color}
                            >
                                {item?.data?.role === UserRoles.SUBADMIN
                                    ? 'Coordinator'
                                    : item?.data?.role}
                            </text>
                        )
                    )}
                    <rect
                        width={item.size?.width}
                        height={item.size?.height}
                        // fill="#F7910F"
                        fill={
                            !item?.data?.role && isTabError
                                ? 'red'
                                : item.data?.color
                        }
                        stroke={item.data?.color}
                        fillOpacity="0.4"
                        strokeWidth={'0.5'}
                    />
                    {/* <rect
                        x="0.5"
                        y="0.5"
                        width={item.size?.width}
                        height={item.size?.height}
                        // stroke="#A9650E"
                        stroke={item.data?.color}
                        fillOpacity={'0'}
                    /> */}

                    <foreignObject
                        x="2"
                        y="5"
                        width={item.size?.width}
                        height={item.size?.height}
                        style={{ background: 'transparent' }} // Ensure it's visible and clickable
                    >
                        <div
                            style={{
                                position: 'relative',
                                overflow: 'hidden',
                                textOverflow: 'ellipsis',
                                whiteSpace: 'nowrap',
                                fontSize: '10px',
                                color: item.data?.color,
                                background: 'transparent', // Ensure it's visible and clickable
                            }}
                            id={`tabs-view-${item?.id}`}
                            className="flex items-center gap-x-1"
                        >
                            <div className=" top-0 left-0 z-50 p-4 bg-white">
                                <button onClick={handleClick}>Sign</button>
                            </div>
                        </div>
                    </foreignObject>
                    {/* <text
                        className="text-[10px]"
                        x="6"
                        y="16"
                        style={{
                            whiteSpace: 'nowrap', // Prevent line breaks
                            textOverflow: 'ellipsis', // Display an ellipsis (...) if the text overflows
                            overflow: 'hidden', // Hide the overflow
                            maxWidth: '10', // Set your desired maximum width
                            fontSize: '10px', // Set your desired font size
                            fill: item.data?.color,
                        }}
                        // textLength="12" // Set the desired width
                        // lengthAdjust="spacingAndGlyphs"
                    >
                        {item.data?.placeholder || 'Text'}
                    </text> */}
                </>
            )}

            {item.selected && (
                <RubberBand
                    item={item}
                    onResize={onResize}
                    onResized={onResized}
                    checkBox={item?.data?.type === FieldsTypeEnum.Checkbox}
                />
            )}
        </g>
    )
}
