import { useDraggable } from '@dnd-kit/core'
import { CSS } from '@dnd-kit/utilities'
import { useEffect, useRef, useState } from 'react'
import { TextInput } from '@components/inputs'
import { UserRoles } from '@constants'
import { FieldsTypeEnum } from '@components/Esign/components/SidebarData'
import { RubberBand } from '@components/Esign'
import SignatureCanvas from 'react-signature-canvas'
import { Button } from '@components/buttons'

export const LogbookDraggableTab = ({
    item,
    onResize,
    onResized,
    onItemSelected,
    onRemove,
    tabsError,
    viewport,
}: any) => {
    const { attributes, listeners, setNodeRef, transform }: any = useDraggable({
        id: `input-tab-${item.id}`,
        data: { ...item, dataLabel: 'autogenerated-datalabel', viewport },
    })

    const [selectedIIII, setSelectedIIII] = useState<any>({})

    const handleClick = (e: any) => {
        console.log(item?.id, 'IIIIII')
        e?.stopPropagation()
        setSelectedIIII({
            ...selectedIIII,
            selected: false,
        })
    }

    const [position, setPosition] = useState({ x: 0, y: 0 })
    const [dragging, setDragging] = useState(false)
    const offset = useRef({ x: 0, y: 0 })

    const handleMouseDown = (e: any) => {
        e?.stopPropagation()
        setDragging(true)
        // Capture initial offset
        offset.current = {
            x: e.clientX - position.x,
            y: e.clientY - position.y,
        }
        console.log({ item })
        setSelectedIIII(item)
        onItemSelected(item, !item.selected, true)
    }

    const handleMouseMove = (e: any) => {
        e?.stopPropagation()
        if (dragging) {
            // Calculate new position
            const newPosition = {
                x: e.clientX - offset.current.x,
                y: e.clientY - offset.current.y,
            }

            // Update position using requestAnimationFrame for smoothness
            requestAnimationFrame(() => setPosition(newPosition))
        }
    }

    const handleMouseUp = (e: any) => {
        e?.stopPropagation()
        setDragging(false)
    }

    useEffect(() => {
        // Attach the mousemove and mouseup listeners to the document
        if (dragging) {
            document.addEventListener('mousemove', handleMouseMove)
            document.addEventListener('mouseup', handleMouseUp)
        } else {
            // Cleanup the listeners when dragging stops
            document.removeEventListener('mousemove', handleMouseMove)
            document.removeEventListener('mouseup', handleMouseUp)
        }

        // Cleanup listeners on component unmount
        return () => {
            document.removeEventListener('mousemove', handleMouseMove)
            document.removeEventListener('mouseup', handleMouseUp)
        }
    }, [dragging])
    const [isTabError, setIsTabError] = useState(false)

    useEffect(() => {
        if (
            tabsError &&
            tabsError?.map((tab: any) => tab.id).includes(item?.id)
        ) {
            setIsTabError(true)
        }
        if (item?.data?.role) {
            setIsTabError(false)
        }
    }, [item?.data?.role, tabsError])

    // const style = {
    //     x: transform.x + item.location?.x,
    //     y: transform.y + item.location?.y,
    //     scaleX: transform?.scaleX,
    //     scaleY: transform?.scaleY,
    // }
    // const style = {
    //     ...(transform
    //         ? {
    //               transform: CSS.Translate.toString({
    //                   x: transform.x + item.location?.x,
    //                   y: transform.y + item.location?.y,
    //                   scaleX: transform?.scaleX,
    //                   scaleY: transform?.scaleY,
    //               }),
    //           }
    //         : {}),
    // }

    return (
        <g
            id={item?.id}
            data-view-name="tab"
            data-view-id=""
            cursor={'grab'}
            // ref={setNodeRef}
            className="outline-none z-50"
            // {...(item.moving
            //     ? { style: { ...style } }
            //     : {
            //           transform: `matrix(1 0 0 1 ${item.location.x} ${item.location.y})`,
            //       })}
            // onMouseDown={(e: any) => {
            //     console.log({ itemitemitemitemitem: item })
            //     onItemSelected(item, !item.selected, true)
            // }}
            // {...listeners}
            // onKeyDown={(e: any) => {
            //     var key = e.which || e.keyCode || e.charCode
            //     if (key == 8 || key == 46) {
            //         onRemove(item)
            //     }

            //     listeners.onKeyDown(e)
            // }}
            style={{ transform: `translate(${position.x}px, ${position.y}px)` }}
            onMouseDown={handleMouseDown}
            // {...attributes}
        >
            {item?.data?.type === FieldsTypeEnum.Checkbox ? (
                <>
                    <rect
                        x="0"
                        y="0"
                        width="11"
                        height="11"
                        fill={
                            !item?.data?.role && isTabError
                                ? 'red'
                                : item.data?.color
                        }
                        stroke="black"
                        strokeWidth="1"
                        // onClick={handleCheckboxChange}
                    />
                    <text x="2" y="9" className="text-[9px]" fill={'white'}>
                        ✔
                    </text>
                </>
            ) : (
                <>
                    {!item?.data?.role && isTabError ? (
                        <>
                            <rect
                                x="0" // Adjust the x-coordinate to move the background closer to the text
                                y="-9" // Adjust the y-coordinate to move the background closer to the text
                                width={item.size?.width} // Adjust the width to reduce the size of the background
                                height="8" // Adjust the height to reduce the size of the background
                                fill="white" // Replace 'yellow' with the desired background color
                                fillOpacity="1"
                            />
                            <text
                                x="2"
                                y="-2"
                                className="text-[7px] "
                                fill={'red'}
                            >
                                Please Select the role
                            </text>
                        </>
                    ) : (
                        item?.data?.isCustom && (
                            <text
                                style={{
                                    backgroundColor: 'yellow',
                                    fontSize: '7px',
                                    color: item.data?.color,
                                }}
                                className="uppercase"
                                x="2"
                                y="-2"
                                // fill={item.data?.color}
                            >
                                {item?.data?.role === UserRoles.SUBADMIN
                                    ? 'Coordinator'
                                    : item?.data?.role}
                            </text>
                        )
                    )}
                    <rect
                        width={item.size?.width}
                        height={item.size?.height}
                        // fill="#F7910F"
                        fill={
                            !item?.data?.role && isTabError
                                ? 'red'
                                : item.data?.color
                        }
                        stroke={item.data?.color}
                        fillOpacity="0.4"
                        strokeWidth={'0.5'}
                    />
                    {/* <rect
                        x="0.5"
                        y="0.5"
                        width={item.size?.width}
                        height={item.size?.height}
                        // stroke="#A9650E"
                        stroke={item.data?.color}
                        fillOpacity={'0'}
                    /> */}

                    <foreignObject
                        x="2"
                        y="5"
                        width={item.size?.width}
                        height={item.size?.height}
                        style={{ background: 'transparent' }} // Ensure it's visible and clickable
                    >
                        <div
                            style={{
                                position: 'relative',
                                overflow: 'hidden',
                                textOverflow: 'ellipsis',
                                whiteSpace: 'nowrap',
                                fontSize: '10px',
                                color: item.data?.color,
                                background: 'transparent', // Ensure it's visible and clickable
                            }}
                            id={`tabs-view-${item?.id}`}
                            className="flex items-center gap-x-1"
                        >
                            <div className="relative top-0 left-0 z-50 p-4 bg-white">
                                <Button onClick={handleClick}>Sign</Button>
                            </div>
                        </div>
                    </foreignObject>
                    {/* <text
                        className="text-[10px]"
                        x="6"
                        y="16"
                        style={{
                            whiteSpace: 'nowrap', // Prevent line breaks
                            textOverflow: 'ellipsis', // Display an ellipsis (...) if the text overflows
                            overflow: 'hidden', // Hide the overflow
                            maxWidth: '10', // Set your desired maximum width
                            fontSize: '10px', // Set your desired font size
                            fill: item.data?.color,
                        }}
                        // textLength="12" // Set the desired width
                        // lengthAdjust="spacingAndGlyphs"
                    >
                        {item.data?.placeholder || 'Text'}
                    </text> */}
                </>
            )}

            {/* {selectedIIII?.selected && (
                <RubberBand
                    item={selectedIIII}
                    onResize={onResize}
                    onResized={onResized}
                    checkBox={item?.data?.type === FieldsTypeEnum.Checkbox}
                />
            )} */}
        </g>
    )
}
