import { Call } from "./components/call";

export const mockCalls: Call[] = [
    {
        id: '1',
        studentName: 'Sarah Johnson',
        agentName: 'Emma Wilson',
        status: 'open',
        date: '2025-12-15T10:30:00',
        duration: '12:45',
        phoneNumber: '+1 (555) 123-4567',
        industry: 'Healthcare',
        placementCompany: 'City General Hospital',
        notes: 'Student expressed concerns about placement hours. Needs discussion about scheduling flexibility. Follow-up required within 2 days.',
        tags: ['urgent', 'scheduling'],
        priority: 'high',
        recordingUrl: 'https://example.com/recordings/call-001.mp3',
    },
    {
        id: '2',
        studentName: 'Michael Chen',
        agentName: 'James Brown',
        status: 'open',
        date: '2025-12-15T09:15:00',
        duration: '8:20',
        phoneNumber: '+1 (555) 234-5678',
        industry: 'Technology',
        notes: 'Initial onboarding call completed. Student very enthusiastic about IT placement. Discussed expectations and documentation requirements.',
        tags: ['onboarding', 'IT'],
        priority: 'medium',
        recordingUrl: 'https://example.com/recordings/call-002.mp3',
    },
    {
        id: '3',
        studentName: 'Emily Rodriguez',
        agentName: 'Sophie Martinez',
        status: 'completed',
        date: '2025-12-14T15:45:00',
        duration: '18:30',
        phoneNumber: '+1 (555) 345-6789',
        industry: 'Education',
        placementCompany: 'Riverside Elementary',
        notes: 'Excellent placement completion. Student provided positive feedback about mentorship. All documentation collected. Certificate issued.',
        tags: ['completed', 'positive-feedback'],
        priority: 'low',
        recordingUrl: 'https://example.com/recordings/call-003.mp3',
    },
    {
        id: '4',
        studentName: 'David Kim',
        agentName: 'Emma Wilson',
        status: 'open',
        date: '2025-12-14T14:20:00',
        duration: '15:10',
        phoneNumber: '+1 (555) 456-7890',
        industry: 'Finance',
        placementCompany: 'Global Investments Ltd',
        notes: 'Industry partner raised concerns about student attendance. Need to schedule meeting with all parties to address issues.',
        tags: ['attendance', 'urgent'],
        priority: 'high',
        recordingUrl: 'https://example.com/recordings/call-004.mp3',
    },
    {
        id: '5',
        studentName: 'Jessica Taylor',
        agentName: 'James Brown',
        status: 'completed',
        date: '2025-12-14T11:00:00',
        duration: '22:15',
        phoneNumber: '+1 (555) 567-8901',
        industry: 'Marketing',
        placementCompany: 'Creative Agency Co',
        notes: 'Final call with industry partner. Discussed student performance - exceeded expectations. Partner interested in hiring student post-graduation.',
        tags: ['completed', 'hire-potential'],
        priority: 'low',
        recordingUrl: 'https://example.com/recordings/call-005.mp3',
    },
    {
        id: '6',
        studentName: 'Alex Thompson',
        agentName: 'Sophie Martinez',
        status: 'open',
        date: '2025-12-13T16:30:00',
        duration: '10:05',
        phoneNumber: '+1 (555) 678-9012',
        industry: 'Engineering',
        placementCompany: 'Tech Solutions Inc',
        notes: 'Student requested extension for project submission. Need to coordinate with industry partner and academic advisor.',
        tags: ['extension', 'coordination'],
        priority: 'medium',
        recordingUrl: 'https://example.com/recordings/call-006.mp3',
    },
    {
        id: '7',
        studentName: 'Olivia Brown',
        agentName: 'Emma Wilson',
        status: 'open',
        date: '2025-12-13T13:45:00',
        duration: '9:30',
        phoneNumber: '+1 (555) 789-0123',
        industry: 'Hospitality',
        notes: 'New student orientation completed. Covered safety protocols, expectations, and placement timeline. Student ready to begin next week.',
        tags: ['orientation', 'hospitality'],
        priority: 'medium',
        recordingUrl: 'https://example.com/recordings/call-007.mp3',
    },
    {
        id: '8',
        studentName: 'Marcus Williams',
        agentName: 'James Brown',
        status: 'open',
        date: '2025-12-12T10:15:00',
        duration: '14:40',
        phoneNumber: '+1 (555) 890-1234',
        industry: 'Construction',
        placementCompany: 'BuildRight Contractors',
        notes: 'Industry partner needs updated insurance documentation. Follow-up to ensure compliance requirements are met before placement continues.',
        tags: ['documentation', 'compliance'],
        priority: 'high',
        recordingUrl: 'https://example.com/recordings/call-008.mp3',
    },
    {
        id: '9',
        studentName: 'Sophia Lee',
        agentName: 'Sophie Martinez',
        status: 'completed',
        date: '2025-12-11T14:00:00',
        duration: '20:25',
        phoneNumber: '+1 (555) 901-2345',
        industry: 'Design',
        placementCompany: 'Studio Design House',
        notes: 'Placement successfully completed. Student developed strong portfolio during placement. Discussed career opportunities and networking strategies.',
        tags: ['completed', 'portfolio'],
        priority: 'low',
        recordingUrl: 'https://example.com/recordings/call-009.mp3',
    },
    {
        id: '10',
        studentName: 'Daniel Martinez',
        agentName: 'Emma Wilson',
        status: 'open',
        date: '2025-12-11T09:30:00',
        duration: '11:15',
        phoneNumber: '+1 (555) 012-3456',
        industry: 'Retail',
        placementCompany: 'Fashion Forward Stores',
        notes: 'Student reported difficulty with supervisor communication. Need to facilitate mediation session and provide conflict resolution support.',
        tags: ['mediation', 'urgent'],
        priority: 'high',
        recordingUrl: 'https://example.com/recordings/call-010.mp3',
    },
]
