export const MoUData = [
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/34",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "5 Days Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/35",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "6 Months Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/33",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "2 Years Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/32",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "2 Days Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/31",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "2 Months Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/34",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "5 Days Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/35",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "6 Months Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/33",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "2 Years Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/32",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "2 Days Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/31",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "2 Months Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/34",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "5 Days Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/35",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "6 Months Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/33",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "2 Years Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/32",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "2 Days Ago",
    // Action: "Select",
  },
  {
    name: "Example Name Here",
    email : "abc@gmail.com",
    image : "https://picsum.photos/30/31",
    Location: "Malbourne",
    ContactPerson: "John Doe",
    students: 80,
    createdAt : "2 Months Ago",
    // Action: "Select",
  },
];