import { configureStore } from '@reduxjs/toolkit'
// Or from '@reduxjs/toolkit/query/react'
import { setupListeners } from '@reduxjs/toolkit/query'

import {
    availableShiftsApi,
    authApi,
    commonApi,
    rtoCoursesApi,
    studentJobsApi,
    rtoCoordinatorsApi,
    subAdminSettingApi,
    setUnAvailabilityApi,
    industryStudentsApi,
    rtoAppointmentsApi,
    industryCourseApi,
    subAdminAppointmentApi,
    jobsApi,
    setScheduleApi,
    studentSignUpApi,
    studentCoursesApi,
    workplaceRequestApi,
    studentAppointmentsApi,
    studentAssessmentEvidenceApi,
    rtoStudentsApi,
    notesApi,
    rtoWorkplacesApi,
    rtoAssessmentToolsApi,
    subAdminRtosApi,
    subAdminIndustriesApi,
    industryWorkplaceApi,
    assessmentEvidenceApi,
    folderApi,
    rtpMOUApi,
    adminApi,
    messageApi,
    studentAssessmentApi,
    rtoIndustriesApi,
    studentFindAbnApi,
    studentProfileApi,
    mouApi,
    employeeApi,
    employeeTaskApi,
    industryAppointmentApi,
    rtoApi,
    subAdminApi,
    industriesApi,
    rplApi,
} from '@queries'

export const store = configureStore({
    reducer: {
        // Add the generated reducer as a specific top-level slice
        [authApi.reducerPath]: authApi.reducer,
        [availableShiftsApi.reducerPath]: availableShiftsApi.reducer,
        [commonApi.reducerPath]: commonApi.reducer,
        [rtoCoursesApi.reducerPath]: rtoCoursesApi.reducer,
        [rtoCoordinatorsApi.reducerPath]: rtoCoordinatorsApi.reducer,
        [rtoAppointmentsApi.reducerPath]: rtoAppointmentsApi.reducer,
        [industryAppointmentApi.reducerPath]: industryAppointmentApi.reducer,
        [subAdminAppointmentApi.reducerPath]: subAdminAppointmentApi.reducer,
        [messageApi.reducerPath]: messageApi.reducer,
        [subAdminSettingApi.reducerPath]: subAdminSettingApi.reducer,
        [setUnAvailabilityApi.reducerPath]: setUnAvailabilityApi.reducer,
        [setScheduleApi.reducerPath]: setScheduleApi.reducer,
        [rtpMOUApi.reducerPath]: rtpMOUApi.reducer,
        [industryStudentsApi.reducerPath]: industryStudentsApi.reducer,
        [folderApi.reducerPath]: folderApi.reducer,
        [industryCourseApi.reducerPath]: industryCourseApi.reducer,
        [employeeTaskApi.reducerPath]: employeeTaskApi.reducer,
        [employeeApi.reducerPath]: employeeApi.reducer,
        [jobsApi.reducerPath]: jobsApi.reducer,
        [notesApi.reducerPath]: notesApi.reducer,
        [adminApi.reducerPath]: adminApi.reducer,
        [rtoStudentsApi.reducerPath]: rtoStudentsApi.reducer,
        [rtoWorkplacesApi.reducerPath]: rtoWorkplacesApi.reducer,
        [assessmentEvidenceApi.reducerPath]: assessmentEvidenceApi.reducer,
        [industryWorkplaceApi.reducerPath]: industryWorkplaceApi.reducer,
        [rtoAssessmentToolsApi.reducerPath]: rtoAssessmentToolsApi.reducer,
        [subAdminRtosApi.reducerPath]: subAdminRtosApi.reducer,
        [subAdminIndustriesApi.reducerPath]: subAdminIndustriesApi.reducer,
        [studentJobsApi.reducerPath]: studentJobsApi.reducer,
        [studentCoursesApi.reducerPath]: studentCoursesApi.reducer,
        [workplaceRequestApi.reducerPath]: workplaceRequestApi.reducer,
        [studentAppointmentsApi.reducerPath]: studentAppointmentsApi.reducer,
        [studentAssessmentEvidenceApi.reducerPath]:
            studentAssessmentEvidenceApi.reducer,
        [studentSignUpApi.reducerPath]: studentSignUpApi.reducer,
        [studentAssessmentApi.reducerPath]: studentAssessmentApi.reducer,

        [rtoIndustriesApi.reducerPath]: rtoIndustriesApi.reducer,
        [studentFindAbnApi.reducerPath]: studentFindAbnApi.reducer,
        [studentProfileApi.reducerPath]: studentProfileApi.reducer,
        [mouApi.reducerPath]: mouApi.reducer,

        [rtoApi.reducerPath]: rtoApi.reducer,
        [subAdminApi.reducerPath]: subAdminApi.reducer,

        [industriesApi.reducerPath]: industriesApi.reducer,
        [rplApi.reducerPath]: rplApi.reducer,
    },
    // Adding the api middleware enables caching, invalidation, polling,
    // and other useful features of `rtk-query`.
    middleware: (getDefaultMiddleware) =>
        getDefaultMiddleware().concat([
            authApi.middleware,
            availableShiftsApi.middleware,
            commonApi.middleware,
            rtoCoursesApi.middleware,
            rtoCoordinatorsApi.middleware,
            industryAppointmentApi.middleware,
            subAdminAppointmentApi.middleware,
            messageApi.middleware,
            rtoAppointmentsApi.middleware,
            rtoWorkplacesApi.middleware,
            subAdminSettingApi.middleware,
            setUnAvailabilityApi.middleware,
            rtoAssessmentToolsApi.middleware,
            setScheduleApi.middleware,
            rtpMOUApi.middleware,
            industryStudentsApi.middleware,
            folderApi.middleware,
            industryCourseApi.middleware,
            employeeTaskApi.middleware,
            employeeApi.middleware,
            adminApi.middleware,
            jobsApi.middleware,
            notesApi.middleware,
            rtoStudentsApi.middleware,
            studentJobsApi.middleware,
            assessmentEvidenceApi.middleware,
            studentCoursesApi.middleware,
            workplaceRequestApi.middleware,
            industryWorkplaceApi.middleware,
            studentAppointmentsApi.middleware,
            studentAssessmentEvidenceApi.middleware,
            subAdminIndustriesApi.middleware,
            studentAssessmentApi.middleware,
            subAdminRtosApi.middleware,

            rtoIndustriesApi.middleware,
            rtoAssessmentToolsApi.middleware,
            studentFindAbnApi.middleware,
            studentProfileApi.middleware,
            mouApi.middleware,

            rtoApi.middleware,
            subAdminApi.middleware,
            industriesApi.middleware,
            rplApi.middleware,
        ]),
})

// optional, but required for refetchOnFocus/refetchOnReconnect behaviors
// see `setupListeners` docs - takes an optional callback as the 2nd arg for customization
setupListeners(store.dispatch)
