import { configureStore } from '@reduxjs/toolkit'
// Or from '@reduxjs/toolkit/query/react'
import { setupListeners } from '@reduxjs/toolkit/query'

import {
    authApi,
    studentJobsApi,
    subAdminSettingApi,
    setUnAvailabilityApi,
    industryStudentsApi,
    industryCourseApi,
    jobsApi,
    setScheduleApi,
    studentCoursesApi,
    workplaceRequestApi,
    subAdminWorkplaceApi,
    studentAppointmentsApi,
    studentAssessmentEvidenceApi,
    rtoStudentsApi,
    notesApi,
    rtoWorkplacesApi,
    rtoAssessmentToolsApi,
    subAdminRtosApi,
    subAdminIndustriesApi,
    subAdminStudentsApi,
    industryWorkplaceApi,
    assessmentEvidenceApi,
    folderApi,
    rtpMOUApi,
    adminApi,
    messageApi,
    studentAssessmentApi,
    rtoIndustriesApi,
    studentFindAbnApi,
    studentProfileApi,
    mouApi,
    employeeApi,
    employeeTaskApi,
} from '@queries'

export const store = configureStore({
    reducer: {
        // Add the generated reducer as a specific top-level slice
        [authApi.reducerPath]: authApi.reducer,
        [messageApi.reducerPath]: messageApi.reducer,
        [subAdminSettingApi.reducerPath]: subAdminSettingApi.reducer,
        [setUnAvailabilityApi.reducerPath]: setUnAvailabilityApi.reducer,
        [setScheduleApi.reducerPath]: setScheduleApi.reducer,
        [rtpMOUApi.reducerPath]: rtpMOUApi.reducer,
        [industryStudentsApi.reducerPath]: industryStudentsApi.reducer,
        [folderApi.reducerPath]: folderApi.reducer,
        [industryCourseApi.reducerPath]: industryCourseApi.reducer,
        [employeeTaskApi.reducerPath]: employeeTaskApi.reducer,
        [employeeApi.reducerPath]: employeeApi.reducer,
        [jobsApi.reducerPath]: jobsApi.reducer,
        [notesApi.reducerPath]: notesApi.reducer,
        [adminApi.reducerPath]: adminApi.reducer,
        [rtoStudentsApi.reducerPath]: rtoStudentsApi.reducer,
        [rtoWorkplacesApi.reducerPath]: rtoWorkplacesApi.reducer,
        [assessmentEvidenceApi.reducerPath]: assessmentEvidenceApi.reducer,
        [industryWorkplaceApi.reducerPath]: industryWorkplaceApi.reducer,
        [rtoAssessmentToolsApi.reducerPath]: rtoAssessmentToolsApi.reducer,
        [subAdminRtosApi.reducerPath]: subAdminRtosApi.reducer,
        [subAdminIndustriesApi.reducerPath]: subAdminIndustriesApi.reducer,
        [studentJobsApi.reducerPath]: studentJobsApi.reducer,
        [studentCoursesApi.reducerPath]: studentCoursesApi.reducer,
        [workplaceRequestApi.reducerPath]: workplaceRequestApi.reducer,
        [studentAppointmentsApi.reducerPath]: studentAppointmentsApi.reducer,
        [subAdminWorkplaceApi.reducerPath]: subAdminWorkplaceApi.reducer,
        [studentAssessmentEvidenceApi.reducerPath]:
            studentAssessmentEvidenceApi.reducer,
        [subAdminStudentsApi.reducerPath]: subAdminStudentsApi.reducer,
        [studentAssessmentApi.reducerPath]: studentAssessmentApi.reducer,

        [rtoIndustriesApi.reducerPath]: rtoIndustriesApi.reducer,
        [studentFindAbnApi.reducerPath]: studentFindAbnApi.reducer,
        [studentProfileApi.reducerPath]: studentProfileApi.reducer,
        [mouApi.reducerPath]: mouApi.reducer,
    },
    // Adding the api middleware enables caching, invalidation, polling,
    // and other useful features of `rtk-query`.
    middleware: (getDefaultMiddleware) =>
        getDefaultMiddleware().concat([
            authApi.middleware,
            messageApi.middleware,
            subAdminSettingApi.middleware,
            setUnAvailabilityApi.middleware,
            setScheduleApi.middleware,
            rtpMOUApi.middleware,
            industryStudentsApi.middleware,
            folderApi.middleware,
            industryCourseApi.middleware,
            employeeTaskApi.middleware,
            employeeApi.middleware,
            adminApi.middleware,
            jobsApi.middleware,
            notesApi.middleware,
            rtoStudentsApi.middleware,
            studentJobsApi.middleware,
            assessmentEvidenceApi.middleware,
            studentCoursesApi.middleware,
            workplaceRequestApi.middleware,
            subAdminWorkplaceApi.middleware,
            industryWorkplaceApi.middleware,
            studentAppointmentsApi.middleware,
            studentAssessmentEvidenceApi.middleware,
            subAdminIndustriesApi.middleware,
            studentAssessmentApi.middleware,

            rtoIndustriesApi.middleware,
            studentFindAbnApi.middleware,
            studentProfileApi.middleware,
            mouApi.middleware,
        ]),
})

// optional, but required for refetchOnFocus/refetchOnReconnect behaviors
// see `setupListeners` docs - takes an optional callback as the 2nd arg for customization
setupListeners(store.dispatch)
