export interface IWorkplaceIndustries {
  approvalStatus: string
  cancelledAt: string
  cancelledBy: string
  createdAt: string
  currentQualification: string
  currentWork: string
  haveDrivingLicense: boolean
  haveTransport: boolean
  id: number
  isActive: boolean
  isCancelled: boolean
  prefferableLocation: string
  status: string
  updatedAt: string
  industries: {
    AgreementSigned: boolean
    AgreementSignedDate: string
    accepted: boolean
    applied: boolean
    appliedDate: string
    appointmentBooked: boolean
    appointmentBookedDate: string
    awaitingAgreementSigned: boolean
    awaitingAgreementSignedDate: string
    awaitingWorkplaceResponse: boolean
    awaitingWorkplaceResponseDate: string
    cancelled: boolean
    cancelledDate: string
    caseOfficerAssigned: boolean
    caseOfficerAssignedDate: string
    createdAt: string
    id: number
    industryCheck: boolean
    industryCheckDate: string
    industryResponse: string
    industryResponseDate: string
    interview: boolean
    interviewDate: string
    isActive: boolean
    isCompleted: boolean
    isCompletedDate: string
    placementStarted: boolean
    placementStartedDate: string
    terminated: boolean
    terminatedDate: string
    updatedAt: string
    industry: {
      abn: string
      addressLine1: string
      addressLine2: string
      businessName: string
      contactPerson: string
      contactPersonNumber: string
      createdAt: string
      id: number
      isActive: boolean
      location: string
      phoneNumber: string
      state: string
      studentCapacity: number
      suburb: string
      updatedAt: string
      zipCode: string
      courses: {
        code: string
        createdAt: string
        description: string
        hours: number
        id: number
        isActive: boolean
        requirements: string
        title: string
        updatedAt: string
      }[]
    }
  }[]
  student: {
    addressLine1: string
    addressLine2: string
    createdAt: string
    dob: string
    emergencyPerson: string
    emergencyPersonPhone: string
    familyName: string
    id: number
    isActive: boolean
    location: string
    phone: string
    state: string
    studentId: string
    suburb: string
    updatedAt: string
    zipCode: string
  }
}
