export const initialSchedule = [
    {
        day: 'monday',
        openingTime: '09:00',
        closingTime: '17:00',
        break: false,
        breakStart: null,
        breakEnd: null,
        dayOff: false,
    },
    {
        day: 'tuesday',
        openingTime: '09:00',
        closingTime: '17:00',
        break: false,
        breakStart: null,
        breakEnd: null,
        dayOff: false,
    },
    {
        day: 'wednesday',
        openingTime: '09:00',
        closingTime: '17:00',
        break: false,
        breakStart: null,
        breakEnd: null,
        dayOff: false,
    },
    {
        day: 'thursday',
        openingTime: '09:00',
        closingTime: '17:00',
        break: false,
        breakStart: null,
        breakEnd: null,
        dayOff: false,
    },
    {
        day: 'friday',
        openingTime: '09:00',
        closingTime: '17:00',
        break: false,
        breakStart: null,
        breakEnd: null,
        dayOff: false,
    },
    {
        day: 'saturday',
        openingTime: '09:00',
        closingTime: '17:00',
        break: false,
        breakStart: null,
        breakEnd: null,
        dayOff: false,
    },
    {
        day: 'sunday',
        openingTime: '09:00',
        closingTime: '17:00',
        break: false,
        breakStart: null,
        breakEnd: null,
        dayOff: false,
    },
]
