import { Ticket } from './cards/types'

export const mockTickets: Ticket[] = [
    {
        id: 'TKT-1001',
        studentName: 'Sarah Johnson',
        studentId: 'STU-2024-001',
        team: 'student-services',
        priority: 'high',
        status: 'open',
        phase: 'appointment',
        stageStatus: 'Book Appointment',
        title: 'Student has not booked appointment for 4+ hours',
        description:
            'Auto-escalated: Student has been in "Book Appointment" status for 4 hours without action. Student Services intervention required.',
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        escalationType: 'auto',
        hoursStuck: 6,
        assignedTo: 'Rachel Green',
        tags: ['auto-escalation', 'appointment-booking'],
        notes: [
            {
                id: 'NOTE-001',
                content: 'Student contacted via email. Awaiting response.',
                createdBy: 'Rachel Green',
                createdAt: new Date(
                    Date.now() - 1.5 * 60 * 60 * 1000
                ).toISOString(),
            },
        ],
    },
    {
        id: 'TKT-1002',
        studentName: 'Michael Chen',
        studentId: 'STU-2024-002',
        team: 'industry-sourcing',
        priority: 'critical',
        status: 'in-progress',
        phase: 'agreement',
        stageStatus: 'Agreement Pending',
        title: 'Industry agreement unsigned for 5 hours',
        description:
            'Auto-escalated: Industry partner has not signed the placement agreement. Immediate follow-up required.',
        createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        escalationType: 'auto',
        hoursStuck: 5,
        assignedTo: 'James Wilson',
        tags: ['auto-escalation', 'agreement-pending', 'urgent'],
        industryName: 'TechCorp Solutions',
        industryType: 'Technology & IT Services',
        notes: [
            {
                id: 'NOTE-002',
                content:
                    'Called industry contact. They promised to review and sign by EOD.',
                createdBy: 'James Wilson',
                createdAt: new Date(
                    Date.now() - 2 * 60 * 60 * 1000
                ).toISOString(),
            },
            {
                id: 'NOTE-003',
                content: 'Follow-up email sent with agreement link.',
                createdBy: 'James Wilson',
                createdAt: new Date(
                    Date.now() - 1 * 60 * 60 * 1000
                ).toISOString(),
            },
        ],
    },
    {
        id: 'TKT-1003',
        studentName: 'Emma Davis',
        studentId: 'STU-2024-003',
        team: 'rto',
        priority: 'medium',
        status: 'pending',
        phase: 'agreement',
        stageStatus: 'Agreement Signed',
        title: 'RTO review pending for signed agreement',
        description:
            'Auto-escalated: Signed agreement awaiting RTO review for 4+ hours.',
        createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        escalationType: 'auto',
        hoursStuck: 4,
        assignedTo: 'Patricia Moore',
        tags: ['auto-escalation', 'rto-review'],
        notes: [],
    },
    {
        id: 'TKT-1004',
        studentName: 'Alex Martinez',
        studentId: 'STU-2024-004',
        team: 'student-services',
        priority: 'high',
        status: 'open',
        phase: 'approval',
        stageStatus: 'Student Approved',
        title: 'Student approval stuck for 7 hours',
        description:
            'Auto-escalated: Student has been in "Approved" status without progression to next phase.',
        createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
        escalationType: 'auto',
        hoursStuck: 7,
        assignedTo: 'Monica Ross',
        tags: ['auto-escalation', 'approval-stuck'],
        notes: [],
    },
    {
        id: 'TKT-1005',
        studentName: 'Olivia Brown',
        studentId: 'STU-2024-005',
        team: 'student-services',
        priority: 'medium',
        status: 'resolved',
        phase: 'placement',
        stageStatus: 'Schedule Confirmation',
        title: 'Schedule not added by student',
        description:
            'Auto-escalated: Student did not add placement schedule within required timeframe.',
        createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        resolvedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        escalationType: 'auto',
        hoursStuck: 6,
        resolution:
            'Contacted student via phone. Schedule has been added and confirmed.',
        assignedTo: 'Rachel Green',
        tags: ['auto-escalation', 'schedule-pending', 'resolved'],
        notes: [],
    },
    {
        id: 'TKT-1006',
        studentName: 'James Wilson',
        studentId: 'STU-2024-006',
        team: 'industry-sourcing',
        priority: 'high',
        status: 'in-progress',
        phase: 'approval',
        stageStatus: 'Waiting for Industry',
        title: 'No industry response for 6 hours',
        description:
            'Auto-escalated: Industry partner has not responded to placement request.',
        createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
        escalationType: 'auto',
        hoursStuck: 6,
        assignedTo: 'David Kim',
        tags: ['auto-escalation', 'industry-response'],
        industryName: 'Global Industries Ltd',
        industryType: 'Manufacturing',
        notes: [],
    },
    {
        id: 'TKT-1007',
        studentName: 'Sophie Taylor',
        studentId: 'STU-2024-007',
        team: 'student-services',
        priority: 'low',
        status: 'open',
        phase: 'completion',
        stageStatus: 'Final Verification',
        title: 'Final verification incomplete',
        description:
            'Auto-escalated: Final verification has been pending for 4+ hours.',
        createdAt: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
        escalationType: 'auto',
        hoursStuck: 4.5,
        assignedTo: 'Sarah Parker',
        tags: ['auto-escalation', 'final-verification'],
        notes: [],
    },
    {
        id: 'TKT-1008',
        studentName: 'Daniel Lee',
        studentId: 'STU-2024-008',
        team: 'rto',
        priority: 'high',
        status: 'open',
        phase: 'approval',
        stageStatus: 'Waiting for RTO',
        title: 'Document incorrectly sent to RTO (unsigned)',
        description:
            'Auto-escalated: Document was sent to RTO before student signature was obtained. Requires intervention.',
        createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        escalationType: 'auto',
        assignedTo: 'Michael Brown',
        tags: ['auto-escalation', 'document-error'],
        notes: [],
    },
]
