export * from './AuthLayout'
export * from './UserLayout'
export * from './StudentLayout'
export * from './RtoLayout'
export * from './SubAdminLayout'
export * from './AdminLayout'
export * from './HeadWrapper'
export * from './IndustryLayout'
export * from './SiteLayout'
export * from './SimpleLayout'
export * from './ManagementLayout'
export * from './RtoContactPersonLayout'

export * from './RtoLayoutV2'
