import type { Appointment, GalleryFile } from './types'

export const appointments: Appointment[] = [
    {
        id: 1,
        title: 'Student Placement Interview - Sarah Johnson',
        date: '2024-12-15',
        time: '10:00 AM - 11:00 AM',
        type: 'interview',
        status: 'upcoming',
        location: 'Head Office - Meeting Room 2',
        attendees: ['Sarah Johnson', 'John Smith'],
        description:
            'Initial placement interview for Certificate III in Early Childhood Education',
        color: '#8B5CF6',
        attachments: 2,
    },
    {
        id: 2,
        title: 'Facility Inspection',
        date: '2024-12-18',
        time: '2:00 PM - 3:30 PM',
        type: 'site-visit',
        status: 'upcoming',
        location: 'Northern Branch',
        attendees: ['Michael Chen', 'Emma Wilson'],
        description: 'Quarterly facility safety and compliance inspection',
        color: '#14B8A6',
        attachments: 5,
    },
    {
        id: 3,
        title: 'Virtual Training Session',
        date: '2024-12-20',
        time: '9:00 AM - 12:00 PM',
        type: 'training',
        status: 'upcoming',
        location: 'Online - Zoom',
        attendees: ['All Staff'],
        description: 'Monthly professional development workshop',
        color: '#EC4899',
        attachments: 1,
    },
    {
        id: 4,
        title: 'Progress Review Meeting',
        date: '2024-12-10',
        time: '3:00 PM - 4:00 PM',
        type: 'meeting',
        status: 'completed',
        location: 'Head Office',
        attendees: ['Lisa Anderson', 'David Brown'],
        description: 'Student progress evaluation and feedback session',
        color: '#10B981',
        attachments: 3,
    },
]

export const galleryFiles: GalleryFile[] = [
    {
        id: 1,
        name: 'facility-inspection-report.pdf',
        type: 'pdf',
        size: '2.4 MB',
        uploadedBy: 'John Smith',
        uploadedAt: '2024-12-08 10:30 AM',
        category: 'Reports',
        thumbnail: null,
        relatedAppointment: 2,
    },
    {
        id: 2,
        name: 'student-interview-notes.pdf',
        type: 'pdf',
        size: '856 KB',
        uploadedBy: 'Sarah Johnson',
        uploadedAt: '2024-12-07 2:15 PM',
        category: 'Documents',
        thumbnail: null,
        relatedAppointment: 1,
    },
    {
        id: 3,
        name: 'training-certificate.jpg',
        type: 'image',
        size: '1.2 MB',
        uploadedBy: 'Emma Wilson',
        uploadedAt: '2024-12-06 4:45 PM',
        category: 'Certificates',
        thumbnail:
            'https://images.unsplash.com/photo-1589149098258-3e9102cd63d3?w=400',
        relatedAppointment: 3,
    },
    {
        id: 4,
        name: 'meeting-room-setup.jpg',
        type: 'image',
        size: '3.1 MB',
        uploadedBy: 'Michael Chen',
        uploadedAt: '2024-12-05 11:20 AM',
        category: 'Photos',
        thumbnail:
            'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400',
        relatedAppointment: 4,
    },
    {
        id: 5,
        name: 'safety-checklist.xlsx',
        type: 'excel',
        size: '445 KB',
        uploadedBy: 'Lisa Anderson',
        uploadedAt: '2024-12-04 9:00 AM',
        category: 'Checklists',
        thumbnail: null,
        relatedAppointment: 2,
    },
]
