import { AdminStats, SMSFormQueryType } from '@types'
import { emptySplitApi } from '../empty.query'
import { appointmentTypeEndpoints } from './appointment-type'
import { blogsEndpoints } from './blogs'
import { courseEndpoints } from './course'
import { departmentEndpoints } from './department'
import { documentsEndpoints } from './documents'
import { folderEndpoints } from './folder'
import { generateKeysEndpoints } from './generate-key'
import { industryEndpoints } from './industry'
import { industryRplEndpoints } from './industyRpl'
import { insuranceEndpoints } from './insurance'
import { jobEndpoints } from './job'
import { kpiProgressEndpoints } from './kpiProgress'
import { notesTemplatesEndpoints } from './notesTemplates'
import { profileEndpoints } from './profile'
import { rtoEndpoints } from './rto'
import { sectorEndpoints } from './sector'
import { studentEndpoints } from './student'
import { subAdminEndpoints } from './sub-admin'
import { subscriberEndpoints } from './subscribers'
import { talentPoolEndpoints } from './talentPool'
import { volunteerEndpoints } from './volunteer'
import { workplaceEndpoints } from './workplace'
import { wptypesEndpoints } from './wptypes'
import { sectorDocumentsEndpoints } from './sector-documents'
import { industryChecksEndpoints } from './industry-checks'
import { invoiceEndpoints } from './invoice'
import { rtoEnquiryEndpoints } from './rto-enquiry'
import { rtoMessageCenterEndpoints } from './rto-message-center'

const PREFIX = 'admin'
export const adminApi = emptySplitApi('adminApi').injectEndpoints({
    // ---------- ADMIN ENDPOINTS ---------- //
    endpoints: (build) => ({
        statistics: build.query<AdminStats, void>({
            query: () => `${PREFIX}/count`,
            providesTags: ['Statistics'],
        }),

        sendSMS: build.mutation<
            SMSFormQueryType,
            { number: string; message: string }
        >({
            query: (body) => ({
                url: `${PREFIX}/sms/send`,
                method: 'POST',
                body,
            }),
            invalidatesTags: ['SMS'],
        }),

        sectorsStudentsCount: build.query<any, void>({
            query: () => `${PREFIX}/sectors/count`,
            providesTags: ['Statistics'],
        }),

        allowRtoListing: build.mutation<any, number>({
            query: (id) => ({
                url: `admin/subadmin/${id}/allow-rto/listing`,
                method: 'PATCH',
            }),
            invalidatesTags: ['AllowRtoListing', 'SubAdmins'],
        }),
        allowIndustryListing: build.mutation<any, number>({
            query: (id) => ({
                url: `admin/subadmin/${id}/allow-industry/listing`,
                method: 'PATCH',
            }),
            invalidatesTags: ['AllowRtoListing', 'SubAdmins'],
        }),

        ...rtoEndpoints(build),
        ...jobEndpoints(build),
        ...blogsEndpoints(build),
        ...sectorEndpoints(build),
        ...courseEndpoints(build),
        ...folderEndpoints(build),
        ...studentEndpoints(build),
        ...wptypesEndpoints(build),
        ...sectorDocumentsEndpoints(build),
        ...industryChecksEndpoints(build),
        ...invoiceEndpoints(build),
        ...profileEndpoints(build),
        ...subAdminEndpoints(build),
        ...industryEndpoints(build),
        ...insuranceEndpoints(build),
        ...workplaceEndpoints(build),
        ...volunteerEndpoints(build),
        ...documentsEndpoints(build),
        ...subscriberEndpoints(build),
        ...talentPoolEndpoints(build),
        ...departmentEndpoints(build),
        ...rtoEnquiryEndpoints(build),
        ...kpiProgressEndpoints(build),
        ...industryRplEndpoints(build),
        ...generateKeysEndpoints(build),
        ...notesTemplatesEndpoints(build),
        ...appointmentTypeEndpoints(build),
        ...rtoMessageCenterEndpoints(build),
    }),
    // overrideExisting: false,
})

const {
    // ------ ADMIN ------ //
    useStatisticsQuery,
    useGetProfileQuery,
    useSectorsStudentsCountQuery,
    useUpdateAdminProfileMutation,
    useGetDashboardChartCountsQuery,
    useGetAdminProgressByCourseQuery,

    useAllowRtoListingMutation,
    useAllowIndustryListingMutation,

    // Blogs
    useCreateBlogMutation,
    useGetBlogsQuery,
    useGetFeaturedBlogsQuery,
    useGetBlogDetailQuery,
    useRemoveBlogMutation,
    useRemoveFaqMutation,
    useBulkRemoveBlogMutation,
    useBulkDeleteBlogCategoriesMutation,
    useUpdateBlogMutation,
    useAddBlogTagsMutation,
    useGetTagsQuery,
    useAddBlogCategoriesMutation,
    useDeleteBlogCategoryMutation,
    useGetCategoriesQuery,
    useGetBlogsCountQuery,
    useUploadImageMutation,

    // Departments
    useGetDepartmentCoordinatorsQuery,
    useGetDepartmentFilterListQuery,
    useAddDepartmentMutation,
    useUpdateDepartmentMutation,
    useGetDepartmentsQuery,
    useGetDepartmentDetailsQuery,
    useGetDeptCoordinatorsListQuery,
    useGetDeptCoordinatorsDropdownListQuery,
    useToggleHodMutation,
    useChangeHodMutation,
    useRemoveDepartmentCoordinatorMutation,
    useAddDepartmentMembersMutation,
    useGetDepartmentCountsQuery,
    useGetDepartmentChartStatsQuery,
    useDepartmentCoursesQuery,
    useGetSectorsAddingListQuery,
    useGetDepartmentStudentsForMapQuery,
    useGetDepartmentIndustriesForMapQuery,
    useGetDepartmentFutureIndustriesForMapQuery,
    useGetStudentsSuburbsForMapQuery,
    useDeleteDepartmentMutation,
    useGetDeptStudentsListQuery,
    useGetDepartmentSectorsQuery,
    useGetDepartmentLineChartCountsQuery,

    // ------ KPI ------ //
    useAddKpiTypeMutation,
    useKpiDeptListQuery,
    useKpiTypesListQuery,
    useKpiTargetsListQuery,
    useAddKpiTargetMutation,
    useRemoveTargetMutation,
    useEmployeeCountsQuery,
    useSubadminDetailQuery,
    useSubadminProgressQuery,
    useSubadminReportListQuery,
    useSubadminKpiAppointmentDetailsQuery,
    useSubadminKpiWorkplaceDetailsQuery,
    useSubadminKpiCompletedDetailsQuery,
    useSubadminKpiStudentAgreementDetailsQuery,
    useSubadminKpiWorkplaceAgreementDetailsQuery,
    useSubadminKpiCallIndustriesDetailsQuery,
    useSubadminKpiCallStudentsDetailsQuery,
    useOverAllEmployeeProgressByMonthQuery,
    useSubadminKpiFlagedStudentsDetailsQuery,
    useSubadminKpiSnoozedStudentsDetailsQuery,
    useEmployeeProgressCountsByDeptQuery,
    useOverAllEmployeeProgressCountsQuery,

    // ------ RTO ------ //
    useRtoCountQuery,
    useRtosQuery,
    useRtoDetailQuery,
    useRtosApprovedQuery,
    useRtoRemoveMutation,
    useRtoAutoCompleteMutation,
    useAllowUpdationMutation,
    useRtoStatisticsCountQuery,
    useRtoStatusChangeMutation,
    useRtoStudentsLogsListQuery,
    useRtoAllowPermissionsMutation,
    useRtoWpApprovalRequestMutation,
    useToggleEsignPopulationMutation,
    useCanStudentAddOwnWorkplaceMutation,
    useCanStudentAddNeedWorkplaceMutation,
    useAllowInvoicingPermissionMutation,
    useRtoAllowPartialSubmissionMutation,
    useRtoCreateAssessmentToolsMutation,
    useRtoUpdateAssessmentToolsMutation,
    useRtoRemoveAssessmentToolsMutation,
    useAllowScheduleEmailToggleMutation,
    useRtoAssessmentToolArchiveMutation,
    useRtoCanViewPaymentStatusToggleMutation,
    useCheckStudentEmailMutation,

    useRtoSectorsQuery,
    useRtoAssignCoursesMutation,
    useRtoUnassignCourseMutation,
    useRtoImportStudentsMutation,
    useRtoImportStudentExistingEmailCheckMutation,
    useRtoAddStudentMutation,

    useRtoSubAdminsQuery,
    useRtoAssignSubAdminsMutation,
    useRtoUnassignSubAdminsMutation,
    useRtoProfileSubAdminsQuery,
    useRtoProfileDetailQuery,
    useAutoReleaseLogbookMutation,
    useRtoAssessmentToolsQuery,
    useAllowSelfPaymentMutation,

    // ------ STUDENT ------ //
    useStudentCountQuery,
    useStudentsQuery,
    useGetFlaggedStudentsQuery,
    useStudentProfileQuery,
    useCompletedStudentsQuery,
    useGetSnoozedStudentsQuery,
    useGetUnassignedStudentsQuery,
    useStudentStatusChangeMutation,
    useStudentRemoveMutation,

    useFilteredStudentsQuery,

    useStudentSectorsQuery,
    useStudentAssignCoursesMutation,
    useStudentUnassignCoursesMutation,

    useStudentsRequiredDocsDetailQuery,
    useStudentCourseDetailQuery,
    useStudentPaymentDetailsQuery,
    useStudentUpcomingAppointmentsQuery,

    // ------ INDUSTRY ------ //
    useIndustryStatisticsCountQuery,
    useIndustriesQuery,
    useSnoozedIndustriesQuery,
    useIndustryCountQuery,
    useIndustryDetailQuery,
    useIndustrySectorsQuery,
    useIndustryRemoveMutation,
    useIndustryStudentsQuery,
    useGetIndustryShiftsQuery,
    useAddIndustryShiftMutation,
    useRemoveIndustryShiftMutation,
    useGetIndustryQuestionsQuery,
    useIndustryStatusChangeMutation,
    useSaveIndustryQuestionsMutation,
    useGetIndutryAvailableHoursQuery,
    useAddIndustryServiceOfferedMutation,
    useDeleteIndustryProfileCourseMutation,
    useUpdateIndustryProfileCourseMutation,
    useAddIndutryAvailableHoursMutation,
    useIndustryAssignCoursesMutation,
    useIndustryUnassignCourseMutation,
    useVolunteerIsReadMutation,

    // ----- RPL ----- //
    useRplRequestListQuery,
    useRplDeleteMutation,
    useRplCountQuery,
    useRplIsReadMutation,

    // ------ SECTOR ------ //
    useSectorsQuery,
    useSectorDetailQuery,
    useSectorAddMutation,
    useSectorUpdateMutation,
    useSectorRemoveMutation,

    // ------ COURSES ------ //
    useCoursesQuery,
    useCourseDetailQuery,
    useCourseAddMutation,
    useCourseUpdateMutation,
    useCourseRemoveMutation,
    useSelectedWpTypesQuery,
    useAddWpTypesToCourseMutation,
    useRemoveWpTypesFromCourseMutation,
    useCourseToggleSupersedeMutation,

    // ------ WP-TYPES ------ //
    useWpTypesQuery,
    useWpTypeDetailQuery,
    useAddWpTypeMutation,
    useUpdateWpTypeMutation,
    useRemoveWpTypeMutation,

    // ------ SECTOR-DOCUMENTS ------ //
    useSectorDocumentsQuery,
    useSectorDocumentsBySectorQuery,
    useSectorDocumentDetailQuery,
    useAddSectorDocumentMutation,
    useUpdateSectorDocumentMutation,
    useRemoveSectorDocumentMutation,

    // ------ INDUSTRY-CHECKS ------ //
    useIndustryChecksQuery,
    useIndustryChecksBySectorQuery,
    useIndustryCheckDetailQuery,
    useAddIndustryCheckMutation,
    useUpdateIndustryCheckMutation,
    useRemoveIndustryCheckMutation,

    // ------ SUBSCRIBERS ------ //
    useListSubscribersQuery,
    useResubscribeMutation,
    useUnsubscribeMutation,
    useSubscribeMutation,

    // ------ SUB ADMINS ------ //
    useIsTodoEnabledMutation,
    useToggleIsManagerMutation,
    useUpdateFavIndustriesMutation,
    useToggleCanViewRtoListMutation,
    useToggleCanGlobalSearchMutation,
    useCanApproveRtoWorkplaceMutation,
    useToggleIndustriesAssignmentMutation,
    useToggleCanAccessRTOProfileMutation,
    useToggleCanDownloadReportMutation,
    useToggleCanViewStudentDetailMutation,
    useToggleCanViewIndustryDetailMutation,
    useToggleCanAccessRPLDetailMutation,
    useToggleCanAccessTalentPoolMutation,
    useToggleCanAccessQueriesMutation,
    useToggleCanAccessBlogsMutation,
    useToggleCanAccessSubAdminsMutation,
    useToggleCanAddStudentsMutation,
    useCanImportIndustryListingMutation,
    useCanOnPremiumFeatureMutation,
    useToggleCanCreateInternalTicketMutation,
    useSubAdminsQuery,
    useViewSummaryQuery,
    useSubAdminCountQuery,
    useSubAdminProfileQuery,
    useRemoveWithRtoMutation,
    useSubadminRemoveMutation,
    useCreateSubAdminMutation,
    useUpdateSubAdminMutation,
    useSubAdminAsAdminListQuery,
    useSubAdminsFilterListQuery,
    useSubAdminProfileCountQuery,
    useAssociatedWithRtoMutation,
    useSubadminWorkplaceListQuery,
    useToggleSubadminPlacementMutation,
    useToggleCanViewAllStudentsMutation,
    useToggleWPCancelationRequestMutation,
    useSubAdminExtendedStudentsListQuery,
    useToggleAutoWorkplaceAssignmentMutation,
    useCoordinatorRatingsListQuery,
    useCoordinatorOverallRatingQuery,

    useSubAdminCoursesQuery,
    useSubAdminAssignCoursesMutation,
    useSubAdminUnAssignCoursesMutation,

    useSubAdminRtosQuery,
    useSubAdminAssignRtoMutation,
    useSubAdminUnassignRtoMutation,

    //------ WORKPLACE -----//
    useNeedWpCountQuery,
    useWorkplacesCountQuery,
    useAssignCourseMutation,
    useWpRejectionListQuery,
    useFilteredWorkplacesQuery,
    useCancelledWorkplacesQuery,
    useUnAssignedSubAdminsQuery,
    useAssignedRequestListQuery,
    useAssignedWorkplaceMutation,
    useUnAssignedWorkplaceListQuery,
    useAllRequestedWorkplaceListQuery,
    useWpCancellationRequestsListQuery,
    useBlockedStudentsWorkplaceListQuery,
    usePlacementStartedWorkplaceListQuery,
    useScheduleCompletedWorkplaceListQuery,
    useGetSubadminForAssignWorkplaceQuery,
    useAllStudentProvidedWorkplaceListQuery,
    useChangeStatusForWPCancelationRequestMutation,

    // ------ FOLDERS ------ //
    useFolderAddMutation,
    useFolderUpdateMutation,
    useAssessmentEvidenceUpdateMutation,
    useFolderRemoveMutation,
    useIndustryChecklistAddMutation,
    useAssessmentEvidenceAddMutation,
    useRemoveAssessmentMutation,

    // ------ APPOINTMENT TYPES ------ //
    useAppointmentTypesQuery,
    useAppointmentTypeDetailQuery,
    useAppointmentTypeAddMutation,
    useAppointmentTypeRemoveMutation,
    useAppointmentTypeUpdateMutation,

    // ------ JOBS ------ //
    useJobsQuery,
    useJobApplicantsQuery,
    useJobStatusChangeMutation,

    // --- VOLUNTEER --- //
    useGetVolunteerRequestsQuery,
    useRequestVolunteerCountQuery,
    useChangeVolunteerRequestStatusMutation,

    // ----- SMS ----- //
    useSendSMSMutation,

    // ---- DOCUMENTS ---- //
    useAddDocumentsMutation,
    useGetDocumentsQuery,

    // ---- TALENT POOL ---- //
    useGetTalentPoolListQuery,
    useDeleteTalentPoolProfileMutation,
    useGetTalentPoolProfileQuery,
    useGetTalentPoolProfilesCountQuery,
    useReadTalentPoolProfilesCountMutation,

    // ----- GENERATE KEY ----- //
    useGetKeysQuery,
    useGenerateKeyMutation,
    useDeactivateGeneratedKeyMutation,

    // ---- RTO-OBSERVER ---- //
    useRtoObserverListQuery,
    useAddRtoObserverMutation,
    useRemoveRtoObserverMutation,
    useUpdateRtoObserverMutation,

    // ---- INSURANCE ---- //
    useGetInsuranceTypeQuery,
    useAddInsuranceTypeMutation,
    useEditInsuranceTypeMutation,
    useGetRtoByInsuranceTypeQuery,
    useRemoveInsuranceTypeMutation,
    useGetIndustriesByInsuranceTypeQuery,

    // ---- NOTES TEMPLATES ---- //
    useNotesTemplatesQuery,
    useNotesTemplateDetailQuery,
    useAddNoteTemplateMutation,
    useSwapNoteTemplateMutation,
    useUpdateNoteTemplateMutation,
    useRemoveNoteTemplateMutation,

    // ---- INVOICE ---- //
    useInvoiceRtosListQuery,
    useInvoiceRtoDetailQuery,
    useGetInvoiceStatusQuery,
    useConfirmPaymentMutation,
    useInvoiceRtoDataListQuery,
    useAddCustomInvoiceMutation,
    useConfirmAllPaymentMutation,
    useInvoiceCategorisListQuery,
    useAddInvoiceCategoryMutation,
    useChangePaymentStatusMutation,
    useInvoiceRtoDataDownloadQuery,
    useMarkDuplicateToggleMutation,
    useAddRtoInvoiceSettingMutation,

    // ---- RTO ENQUIRY ---- //
    useCloseEnquiryMutation,
    useGetRtoEnquiriesQuery,
    useAttachIndustryMutation,
    useGetRtoEnquiryDetailQuery,
    useGetRtoEnquiriesCountsQuery,
    usePremiumIndustriesListForEnquiryQuery,

    // ---- RTO MESSAGE CENTER ---- //
    useGetRtosListQuery,
    useSendRtoMessageMutation,
} = adminApi

export const AdminApi = {
    Admin: {
        useCount: useStatisticsQuery,
        useProfile: useGetProfileQuery,
        useUpdateProfile: useUpdateAdminProfileMutation,
        useSectorsStudentsCount: useSectorsStudentsCountQuery,
        useAllowRtoListing: useAllowRtoListingMutation,
        allowIndustryListing: useAllowIndustryListingMutation,
        useDashboardChartCounts: useGetDashboardChartCountsQuery,
        useAdminProgressByCourse: useGetAdminProgressByCourseQuery,
    },
    Department: {
        getDepartmentFilterList: useGetDepartmentFilterListQuery,
        useDepartmentCoordinators: useGetDepartmentCoordinatorsQuery,
        useAddDepartment: useAddDepartmentMutation,
        updateDepartment: useUpdateDepartmentMutation,
        useDepartments: useGetDepartmentsQuery,
        useDepartmentDetails: useGetDepartmentDetailsQuery,
        useDeptCoordinatorsList: useGetDeptCoordinatorsListQuery,
        useDeptCoordinatorsDropdownList:
            useGetDeptCoordinatorsDropdownListQuery,
        useToggleHod: useToggleHodMutation,
        useChangeHod: useChangeHodMutation,
        getSectorsAddingList: useGetSectorsAddingListQuery,
        useRemoveDepartmentCoordinator: useRemoveDepartmentCoordinatorMutation,
        useAddDepartmentMembers: useAddDepartmentMembersMutation,
        useDepartmentCounts: useGetDepartmentCountsQuery,
        useDepartmentChartStats: useGetDepartmentChartStatsQuery,
        useDepartmentCourses: useDepartmentCoursesQuery,
        useDepartmentStudentsForMap: useGetDepartmentStudentsForMapQuery,
        useDepartmentIndustriesForMap: useGetDepartmentIndustriesForMapQuery,
        useDepartmentFutureIndustriesForMap:
            useGetDepartmentFutureIndustriesForMapQuery,
        useStudentsSuburbsForMap: useGetStudentsSuburbsForMapQuery,
        useDeleteDepartment: useDeleteDepartmentMutation,
        useDeptStudentsList: useGetDeptStudentsListQuery,
        useDepartmentSectors: useGetDepartmentSectorsQuery,
        useDepartmentLineChartCounts: useGetDepartmentLineChartCountsQuery,
    },
    Kpi: {
        kpiTypes: useKpiTypesListQuery,
        kpiDeptList: useKpiDeptListQuery,
        addKpiType: useAddKpiTypeMutation,
        removeTarget: useRemoveTargetMutation,
        addKpiTarget: useAddKpiTargetMutation,
        kpiTargetsList: useKpiTargetsListQuery,
        subadminDetail: useSubadminDetailQuery,
        subadminProgress: useSubadminProgressQuery,
        employeeCounts: useEmployeeCountsQuery,
        subadminReportList: useSubadminReportListQuery,
        employeeProgressByDept: useEmployeeProgressCountsByDeptQuery,
        appointmentDetails: useSubadminKpiAppointmentDetailsQuery,
        workplaceDetails: useSubadminKpiWorkplaceDetailsQuery,
        completedDetails: useSubadminKpiCompletedDetailsQuery,
        studentAgreementDetails: useSubadminKpiStudentAgreementDetailsQuery,
        workplaceAgreementDetails: useSubadminKpiWorkplaceAgreementDetailsQuery,
        callIndustries: useSubadminKpiCallIndustriesDetailsQuery,
        callStududents: useSubadminKpiCallStudentsDetailsQuery,
        flaggedStudents: useSubadminKpiFlagedStudentsDetailsQuery,
        snoozedStudents: useSubadminKpiSnoozedStudentsDetailsQuery,
        overAllEmployeeProgressCounts: useOverAllEmployeeProgressCountsQuery,
        overAllEmployeeProgressByMonth: useOverAllEmployeeProgressByMonthQuery,
    },
    Rtos: {
        useCountQuery: useRtoCountQuery,
        useStatisticsCount: useRtoStatisticsCountQuery,
        useListQuery: useRtosQuery,
        useApprovedList: useRtosApprovedQuery,
        useDetailQuery: useRtoDetailQuery,
        useChangeStatusMutation: useRtoStatusChangeMutation,
        rtoWpApprovalRequest: useRtoWpApprovalRequestMutation,
        toggleEsignPopulation: useToggleEsignPopulationMutation,
        useRtoStudentsLogsList: useRtoStudentsLogsListQuery,
        allowPermissions: useRtoAllowPermissionsMutation,
        allowPartialSubmission: useRtoAllowPartialSubmissionMutation,
        allowInvoicingPermission: useAllowInvoicingPermissionMutation,
        canStudentAddOwnWorkplace: useCanStudentAddOwnWorkplaceMutation,
        canStudentAddNeedWorkplace: useCanStudentAddNeedWorkplaceMutation,
        useRemove: useRtoRemoveMutation,
        rtoAutoComplete: useRtoAutoCompleteMutation,
        useCreateAssessmentTools: useRtoCreateAssessmentToolsMutation,
        useAllowUpdation: useAllowUpdationMutation,
        useUpdateAssessmentTools: useRtoUpdateAssessmentToolsMutation,
        useRemoveAssessmentTools: useRtoRemoveAssessmentToolsMutation,
        useArchiveAssessmentTools: useRtoAssessmentToolArchiveMutation,
        rtoCanViewPaymentStatusToggle: useRtoCanViewPaymentStatusToggleMutation,
        allowScheduleEmailToggle: useAllowScheduleEmailToggleMutation,
        useRtoImportStudents: useRtoImportStudentsMutation,
        useRtoAddStudent: useRtoAddStudentMutation,
        useRtoStudentAccountCheck:
            useRtoImportStudentExistingEmailCheckMutation,
        useCheckStudentEmail: useCheckStudentEmailMutation,

        useSectors: useRtoSectorsQuery,
        useAssignCourses: useRtoAssignCoursesMutation,
        useUnassignCourses: useRtoUnassignCourseMutation,

        useSubAdmins: useRtoSubAdminsQuery,
        useAssignSubAdmin: useRtoAssignSubAdminsMutation,
        useUnAssignSubAdmin: useRtoUnassignSubAdminsMutation,
        useRtoProfileSubAdmins: useRtoProfileSubAdminsQuery,

        useRtoAssessmentTools: useRtoAssessmentToolsQuery,
        autoReleaseLogbook: useAutoReleaseLogbookMutation,
        useAllowSelfPayment: useAllowSelfPaymentMutation,
    },

    Students: {
        useListQuery: useStudentsQuery,
        useFlaggedStudents: useGetFlaggedStudentsQuery,
        useProfile: useStudentProfileQuery,
        useCountQuery: useStudentCountQuery,
        useRemove: useStudentRemoveMutation,
        useSnoozedStudents: useGetSnoozedStudentsQuery,
        useCompletedStudents: useCompletedStudentsQuery,
        useChangeStatusMutation: useStudentStatusChangeMutation,
        useUnAssignedStudentsList: useGetUnassignedStudentsQuery,
        useFilteredStudents: useFilteredStudentsQuery,
        useSectors: useStudentSectorsQuery,
        useAssignCourses: useStudentAssignCoursesMutation,
        useUnassignCourses: useStudentUnassignCoursesMutation,
        studentsRequiredDocsDetail: useStudentsRequiredDocsDetailQuery,
        studentCourseDetail: useStudentCourseDetailQuery,
        useStudentPaymentDetails: useStudentPaymentDetailsQuery,
    },

    SubAdmins: {
        useListQuery: useSubAdminsQuery,
        todoEnabled: useIsTodoEnabledMutation,
        toggleIsManager: useToggleIsManagerMutation,
        updateFavIndustries: useUpdateFavIndustriesMutation,
        useCanViewRtoList: useToggleCanViewRtoListMutation,
        useAccessRtoProfile: useToggleCanAccessRTOProfileMutation,
        toggleCanGlobalSearch: useToggleCanGlobalSearchMutation,
        industriesAssignment: useToggleIndustriesAssignmentMutation,
        canApproveRtoWorkplace: useCanApproveRtoWorkplaceMutation,
        useCanDownloadReport: useToggleCanDownloadReportMutation,
        useCanViewStudentDetail: useToggleCanViewStudentDetailMutation,
        useCanViewIndustryDetail: useToggleCanViewIndustryDetailMutation,
        useCanAccessRPLDetail: useToggleCanAccessRPLDetailMutation,
        useCanAccessTalentPool: useToggleCanAccessTalentPoolMutation,
        useCanAccessQueries: useToggleCanAccessQueriesMutation,
        useCanAccessBlogs: useToggleCanAccessBlogsMutation,
        useCanAddStudents: useToggleCanAddStudentsMutation,
        useToggleInternalTicket: useToggleCanCreateInternalTicketMutation,
        useToggleCanAccessSubAdmins: useToggleCanAccessSubAdminsMutation,
        canImportIndustryListing: useCanImportIndustryListingMutation,
        canOnPremiumFeature: useCanOnPremiumFeatureMutation,
        useSubAdminAsAdminList: useSubAdminAsAdminListQuery,
        useSubAdminsFilterList: useSubAdminsFilterListQuery,
        useCountQuery: useSubAdminCountQuery,
        useProfileCount: useSubAdminProfileCountQuery,
        createSubAmin: useCreateSubAdminMutation,
        useSubadminProfile: useSubAdminProfileQuery,
        useUpdate: useUpdateSubAdminMutation,
        useRemove: useSubadminRemoveMutation,
        useRemoveWithRto: useRemoveWithRtoMutation,
        useAssociatedWithRto: useAssociatedWithRtoMutation,
        useSubadminWorkplaceList: useSubadminWorkplaceListQuery,
        useCanViewAllStudents: useToggleCanViewAllStudentsMutation,
        useToggleSubadminPlacement: useToggleSubadminPlacementMutation,
        toggleWPCancelationReq: useToggleWPCancelationRequestMutation,
        subadminExtendedStudents: useSubAdminExtendedStudentsListQuery,
        useToggleAutoAssignWorkplace: useToggleAutoWorkplaceAssignmentMutation,
        useCoordinatorRatingsList: useCoordinatorRatingsListQuery,
        useCoordinatorOverallRating: useCoordinatorOverallRatingQuery,
        useCourses: useSubAdminCoursesQuery,
        useAssignCourses: useSubAdminAssignCoursesMutation,
        useUnassignCourse: useSubAdminUnAssignCoursesMutation,
        useRtos: useSubAdminRtosQuery,
        useAssignRto: useSubAdminAssignRtoMutation,
        useUnassignRto: useSubAdminUnassignRtoMutation,
        useSummary: useViewSummaryQuery,
    },
    Workplace: {
        needWpCount: useNeedWpCountQuery,
        assignCourse: useAssignCourseMutation,
        wpRejectionList: useWpRejectionListQuery,
        workplacesCount: useWorkplacesCountQuery,
        useListQuery: useUnAssignedSubAdminsQuery,
        cancelledWorkplaces: useCancelledWorkplacesQuery,
        useWorkplaceMutation: useAssignedWorkplaceMutation,
        useAssignedWorkplace: useAssignedRequestListQuery,
        useFilteredWorkplaces: useFilteredWorkplacesQuery,
        useUnAssignedWorkplace: useUnAssignedWorkplaceListQuery,
        useRequestedWorkplace: useAllRequestedWorkplaceListQuery,
        blockedStudentsWPList: useBlockedStudentsWorkplaceListQuery,
        wpCancelationRequestsList: useWpCancellationRequestsListQuery,
        placementStartedWPList: usePlacementStartedWorkplaceListQuery,
        completedWorkplaceList: useScheduleCompletedWorkplaceListQuery,
        subadminForAssignWorkplace: useGetSubadminForAssignWorkplaceQuery,
        useStudentProvidedWorkplace: useAllStudentProvidedWorkplaceListQuery,
        changeStatusCancelationReq:
            useChangeStatusForWPCancelationRequestMutation,
    },

    Industries: {
        useCount: useIndustryCountQuery,
        useListQuery: useIndustriesQuery,
        useDetail: useIndustryDetailQuery,
        useRemove: useIndustryRemoveMutation,
        industryStudents: useIndustryStudentsQuery,
        useRemoveShift: useRemoveIndustryShiftMutation,
        useGetIndustryShifts: useGetIndustryShiftsQuery,
        useAddIndustryShift: useAddIndustryShiftMutation,
        useIndustryQuestions: useGetIndustryQuestionsQuery,
        useIndustrySectors: useIndustrySectorsQuery,
        useSnoozedIndustry: useSnoozedIndustriesQuery,
        useStatusChange: useIndustryStatusChangeMutation,
        useAssignCourses: useIndustryAssignCoursesMutation,
        useStatisticsCount: useIndustryStatisticsCountQuery,
        useUnassignCourses: useIndustryUnassignCourseMutation,
        saveIndustryQuestions: useSaveIndustryQuestionsMutation,
        useAddIndustryHours: useAddIndutryAvailableHoursMutation,
        useIndustryAvailableHours: useGetIndutryAvailableHoursQuery,
        addIndustryServiceOffered: useAddIndustryServiceOfferedMutation,
        useDeleteIndustryProfileCourse: useDeleteIndustryProfileCourseMutation,
        useUpdateIndustryProfileCourse: useUpdateIndustryProfileCourseMutation,
    },

    Rpl: {
        useRplList: useRplRequestListQuery,
        useRemoveRpl: useRplDeleteMutation,
        useRplCount: useRplCountQuery,
        useRplRead: useRplIsReadMutation,
    },

    Subscribers: {
        useListQuery: useListSubscribersQuery,
        useResubscribeMutation,
        useUnsubscribeMutation,
        useSubscribe: useSubscribeMutation,
    },

    Sectors: {
        useListQuery: useSectorsQuery,
        useDetailQuery: useSectorDetailQuery,
        useAddMutation: useSectorAddMutation,
        useUpdateMutation: useSectorUpdateMutation,
        useRemoveMutation: useSectorRemoveMutation,
    },

    Courses: {
        useListQuery: useCoursesQuery,
        useDetailQuery: useCourseDetailQuery,
        useAddMutation: useCourseAddMutation,
        selectedWpTypes: useSelectedWpTypesQuery,
        useUpdateMutation: useCourseUpdateMutation,
        useRemoveMutation: useCourseRemoveMutation,
        addWpTypesToCourse: useAddWpTypesToCourseMutation,
        removeWpTypesFromCourse: useRemoveWpTypesFromCourseMutation,
        useCourseToggleSupersede: useCourseToggleSupersedeMutation,
    },

    WpTypes: {
        wpTypes: useWpTypesQuery,
        addWpType: useAddWpTypeMutation,
        wpTypeDetail: useWpTypeDetailQuery,
        updateWpType: useUpdateWpTypeMutation,
        removeWpType: useRemoveWpTypeMutation,
    },

    SectorDocuments: {
        sectorDocuments: useSectorDocumentsQuery,
        sectorDocumentsBySector: useSectorDocumentsBySectorQuery,
        addSectorDocument: useAddSectorDocumentMutation,
        sectorDocumentDetail: useSectorDocumentDetailQuery,
        updateSectorDocument: useUpdateSectorDocumentMutation,
        removeSectorDocument: useRemoveSectorDocumentMutation,
    },

    IndustryChecks: {
        industryChecks: useIndustryChecksQuery,
        industryChecksBySector: useIndustryChecksBySectorQuery,
        addIndustryCheck: useAddIndustryCheckMutation,
        industryCheckDetail: useIndustryCheckDetailQuery,
        updateIndustryCheck: useUpdateIndustryCheckMutation,
        removeIndustryCheck: useRemoveIndustryCheckMutation,
    },

    Folders: {
        useCreate: useFolderAddMutation,
        useUpdate: useFolderUpdateMutation,
        useAssessMentUpdate: useAssessmentEvidenceUpdateMutation,
        useRemove: useFolderRemoveMutation,
        useRemoveAssessment: useRemoveAssessmentMutation,
        useIndustryChecklistAdd: useIndustryChecklistAddMutation,
        useAssessMentEvidence: useAssessmentEvidenceAddMutation,
    },

    AppointmentTypes: {
        useList: useAppointmentTypesQuery,
        useDetail: useAppointmentTypeDetailQuery,
        useCreate: useAppointmentTypeAddMutation,
        useUpdate: useAppointmentTypeUpdateMutation,
        useRemove: useAppointmentTypeRemoveMutation,
    },

    Jobs: {
        useList: useJobsQuery,
        useJobApplicants: useJobApplicantsQuery,
        useStatusChange: useJobStatusChangeMutation,
    },
    Volunteer: {
        useList: useGetVolunteerRequestsQuery,
        useVolunteerRead: useVolunteerIsReadMutation,
        useVolunteerCount: useRequestVolunteerCountQuery,
        changeRequestStatus: useChangeVolunteerRequestStatusMutation,
    },
    SMS: {
        sendSMS: useSendSMSMutation,
    },
    Documents: {
        addDocuments: useAddDocumentsMutation,
        useGetDocuments: useGetDocumentsQuery,
    },
    TalentPool: {
        useTalentPoolRequests: useGetTalentPoolListQuery,
        useDeleteTalentPoolProfile: useDeleteTalentPoolProfileMutation,
        useGetTalentPoolProfile: useGetTalentPoolProfileQuery,
        useTalentProfilesCount: useGetTalentPoolProfilesCountQuery,
        useReadTalentPoolProfilesCount: useReadTalentPoolProfilesCountMutation,
    },
    Blogs: {
        useBlogsCount: useGetBlogsCountQuery,
        uploadImage: useUploadImageMutation,
    },
    GenerateKey: {
        getKeys: useGetKeysQuery,
        generateKey: useGenerateKeyMutation,
        useDeactivateKey: useDeactivateGeneratedKeyMutation,
    },
    RtoObserver: {
        useObserList: useRtoObserverListQuery,
        useRemove: useRemoveRtoObserverMutation,
        useAddRtoObserver: useAddRtoObserverMutation,
        useUpdateRtoObserver: useUpdateRtoObserverMutation,
    },
    Insurance: {
        getInsuranceType: useGetInsuranceTypeQuery,
        addInsuranceType: useAddInsuranceTypeMutation,
        editInsuranceType: useEditInsuranceTypeMutation,
        removeInsuranceType: useRemoveInsuranceTypeMutation,
        getRtoByInsuranceType: useGetRtoByInsuranceTypeQuery,
        industriesByInsuranceType: useGetIndustriesByInsuranceTypeQuery,
    },
    NotesTemplates: {
        notesTemplates: useNotesTemplatesQuery,
        addNoteTemplate: useAddNoteTemplateMutation,
        swapNoteTemplate: useSwapNoteTemplateMutation,
        notesTemplateDetail: useNotesTemplateDetailQuery,
        updateNoteTemplate: useUpdateNoteTemplateMutation,
        removeNoteTemplate: useRemoveNoteTemplateMutation,
    },
    Invoice: {
        invoiceRtosList: useInvoiceRtosListQuery,
        confirmPayment: useConfirmPaymentMutation,
        getInvoiceStatus: useGetInvoiceStatusQuery,
        invoiceRtoDetail: useInvoiceRtoDetailQuery,
        invoiceRtoDataList: useInvoiceRtoDataListQuery,
        addCustomInvoice: useAddCustomInvoiceMutation,
        confirmAllPayment: useConfirmAllPaymentMutation,
        addInvoiceCategory: useAddInvoiceCategoryMutation,
        invoiceCategorisList: useInvoiceCategorisListQuery,
        markDuplicateToggle: useMarkDuplicateToggleMutation,
        changePaymentStatus: useChangePaymentStatusMutation,
        addRtoInvoiceSetting: useAddRtoInvoiceSettingMutation,
        invoiceRtoDataDownload: useInvoiceRtoDataDownloadQuery,
    },
    RtoEnquiry: {
        closeEnquiry: useCloseEnquiryMutation,
        getRtoEnquiries: useGetRtoEnquiriesQuery,
        attachIndustry: useAttachIndustryMutation,
        getRtoEnquiryDetail: useGetRtoEnquiryDetailQuery,
        getRtoEnquiriesCounts: useGetRtoEnquiriesCountsQuery,
        premiumIndustriesList: usePremiumIndustriesListForEnquiryQuery,
    },
    RtoMessageCenter: {
        getRtosList: useGetRtosListQuery,
        sendRtoMessage: useSendRtoMessageMutation,
    },
}
