export enum workplaceQuestionsKeys {
    suburb = 'suburb',
    commutePlan = 'commutePlan',
    supervisorMeeting = 'supervisorMeeting',
    placementStartDate = 'placementStartDate',
    possession = 'possession',
    currentEmploymentStatus = 'currentEmploymentStatus',
    relaventExperience = 'relaventExperience',
    placementGoals = 'placementGoals',
    medicalCondition = 'medicalCondition',
    placementPreferences = 'placementPreferences',
    awarenessOfUnpaidPlacement = 'awarenessOfUnpaidPlacement',
    understandingOfDocumentation = 'understandingOfDocumentation',
    preferredContactTime = 'preferredContactTime',
    autoTalentPool = 'autoTalentPool',
    serviceType = 'serviceType',
}
