export * from './studentJobs.query'
export * from './courses.query'
export * from './workplace.query'
export * from './studentAppontment.query'
export * from './studentAssessmentEvidence.query'
export * from './studentAssessment.query'
export * from './studentFindAbn.query'
export * from './studentProfile.query'
