import { SubAdmin, UserStatus } from '@types'
import { apiSlice } from '../empty.query'
import { subAdminAppointmentspoints } from './appointments'
import { assessmentEvidenceEndpoints } from './assessmentEvidence'
import { deptKpiProgressEndpoints } from './deptKpiProgress'
import { subAdminIndustriesEndpoints } from './industries'
import { studentsLogbookEndpoints } from './logbookSign'
import { notesEndpoints } from './notes'
import { profileEndpoints } from './profile'
import { subAdminReports } from './reports'
import { subAdminRtoEndpoints } from './rto'
import { setScheduleEndpoints } from './setSchedule'
import { subAdminSettingEndpoints } from './setting'
import { setUnavailabilityEndpoints } from './setUnavailability'
import { studentsEndpoints } from './students'
import { talentPoolEndpoints } from './talentPool'
import { todoListEndpoints } from './todoList'
import { subadminVolunteerEndpoints } from './volunteer'
import { workplaceEndpoints } from './workplace'
export const subAdminApi = apiSlice.injectEndpoints({
    // export const subAdminApi = createApi({
    //     reducerPath: 'subAdminApi',
    //     baseQuery: fetchBaseQuery({
    //         baseUrl: `${process.env.NEXT_PUBLIC_END_POINT}/`,
    //         prepareHeaders: (headers, { getState }) => {
    //             const token = AuthUtils.getToken()
    //             if (token) {
    //                 headers.set('authorization', `Bearer ${token}`)
    //             }
    //             return headers
    //         },
    //     }),

    // keepUnusedDataFor: 200,
    // refetchOnMountOrArgChange: true,
    // refetchOnReconnect: true,

    // ---------- Sub Admin ENDPOINTS ---------- //
    endpoints: (build) => ({
        profile: build.query<SubAdmin, void>({
            query: () => `subadmin/me/profile`,
            providesTags: ['SubAdmin'],
        }),

        subadminCourses: build.query<any, void>({
            query: () => `subadmin/courses/list`,
            providesTags: ['SubAdmin'],
        }),

        subadminStatistics: build.query<any, void>({
            query: () => `subadmin/dashboard/count`,
            providesTags: ['Statistics'],
        }),

        changeSubAdminUserStatus: build.mutation<
            any,
            { id: number; status: UserStatus }
        >({
            query: ({ id, status }) => ({
                url: `shared/user/status/update`,
                method: 'PATCH',
                params: { id },
                body: { status },
            }),
            invalidatesTags: [
                'Notes',
                'SubAdmin',
                'SubAdminRtos',
                'SubAdminIndustries',
            ],
        }),

        importRtosList: build.mutation<any, any>({
            query: (body) => ({
                url: `rtolisting/bulk/create`,
                body,
                method: 'POST',
            }),
            invalidatesTags: ['RtosListing'],
        }),
        getAllRtosList: build.query<any, any>({
            query: (params) => ({
                url: `rtolisting`,
                params,
            }),
            providesTags: ['RtosListing'],
        }),
        rtosStatusChange: build.mutation<any, { id: number; status: string }>({
            query: ({ id, status }) => ({
                url: `rtolisting/status-update/${id}`,
                method: 'PATCH',
                body: { status },
            }),
            invalidatesTags: ['RtosListing'],
        }),
        addRtoInListing: build.mutation<any, any>({
            query: (body) => ({
                url: `rtolisting`,
                method: 'POST',
                body,
            }),
            invalidatesTags: ['RtosListing'],
        }),
        updateRtoListing: build.mutation<any, any>({
            query: ({ id, ...body }) => ({
                url: `rtolisting/${id}/update`,
                method: 'PATCH',
                body,
            }),
            invalidatesTags: ['RtosListing'],
        }),
        deleteRtoListing: build.mutation<any, any>({
            query: (id) => ({
                url: `rtolisting/${id}`,
                method: 'DELETE',
            }),
            invalidatesTags: ['RtosListing'],
        }),
        getHodCoordinatorsList: build.query<any, any>({
            query: (params) => ({
                url: `department/hod/coordinators/list`,
                params,
            }),
            providesTags: ['Department'],
        }),
        getCoordinatorsDropDown: build.query<any, void>({
            query: () => `department/hod/coordinators`,
            providesTags: ['SubAdminStudents'],
        }),
        getDepartmentStudents: build.query<any, any>({
            query: (params) => ({
                url: `department/students`,
                params,
            }),
            providesTags: ['SubAdminStudents'],
        }),
        getDepartmentPlacementStartedStudents: build.query<any, any>({
            query: (params) => ({
                url: `department/placement-started/students`,
                params,
            }),
            providesTags: ['SubAdminStudents'],
        }),
        getDepartmentPendingIndustries: build.query<any, any>({
            query: (params) => ({
                url: `department/industries-list`,
                params,
            }),
            providesTags: ['SubAdminIndustries', 'Industries'],
        }),

        getDepartmentStudentsCount: build.query<any, void>({
            query: () => ({
                url: `department/students/count`,
            }),
            providesTags: ['SubAdminStudents'],
        }),
        getDepartmentCoursesRequestList: build.query<any, any>({
            query: (params) => ({
                url: `department/courses/request-list`,
                params,
            }),
            providesTags: ['SubAdminCourses'],
        }),
        departmentCourseRequest: build.mutation<any, any>({
            query: ({ params, body }) => ({
                url: `department/course-request/status`,
                method: 'PATCH',
                params,
                body,
            }),
            invalidatesTags: ['SubAdminCourses', 'RequestToAddCourse'],
        }),

        ...notesEndpoints(build),
        ...subAdminReports(build),
        ...profileEndpoints(build),
        ...studentsEndpoints(build),
        ...todoListEndpoints(build),
        ...workplaceEndpoints(build),
        ...setScheduleEndpoints(build),
        ...subAdminRtoEndpoints(build),
        ...studentsLogbookEndpoints(build),
        ...deptKpiProgressEndpoints(build),
        ...subAdminSettingEndpoints(build),
        ...setUnavailabilityEndpoints(build),
        ...subadminVolunteerEndpoints(build),
        ...subAdminAppointmentspoints(build),
        ...assessmentEvidenceEndpoints(build),
        ...subAdminIndustriesEndpoints(build),
        ...talentPoolEndpoints(build),
    }),
    // overrideExisting: false,
})

export const {
    // ------ SELF ------ //
    useProfileQuery,
    useGlobalSearchListQuery,
    useGetSubAdminMapStudentsQuery,
    useGetSavedCoordinatesQuery,
    useGetSubAdminMapStudentDetailQuery,
    useGetSubAdminMapIndustriesQuery,
    useGetWorkplaceCourseIndustriesQuery,
    useGetWorkplaceListedIndustriesQuery,
    useGetMapIndustriesInRadiusCountQuery,
    useChangeWorkplaceApprovalReqStatusMutation,
    useGetWarningPlacementAndInsuranceDocNoteQuery,
    useGetSubAdminRtosForMapQuery,
    useGetSubAdminStudentSuburbsForMapQuery,
    useSubadminCoursesQuery,
    useUpdateSubAdminProfileMutation,
    useChangeSubAdminUserStatusMutation,
    useSaveCoordinatesForMapMutation,
    useGetHodCoordinatorsListQuery,
    useGetCoordinatorsDropDownQuery,
    useGetDepartmentStudentsQuery,
    useGetDepartmentPlacementStartedStudentsQuery,
    useGetDepartmentStudentsCountQuery,
    useGetDepartmentPendingIndustriesQuery,
    useGetDepartmentCoursesRequestListQuery,
    useDepartmentCourseRequestMutation,
    useAssignCoordinatorToStudentMutation,

    // ----- KPIS ----- //
    useDeptEmployeeCountsQuery,
    useDeptSubadminDetailQuery,
    useVerifyDeptSubadminMutation,
    useDeptEmployeeProgressCountsQuery,
    useDeptEmployeeProgressByMonthQuery,
    useDeptKpiTargetListQuery,
    useSaveDeptKpiTargetMutation,
    useDeptSubadminReportListQuery,

    // -------- Rtos Listing --------//
    useImportRtosListMutation,
    useGetAllRtosListQuery,
    useRtosStatusChangeMutation,
    useAddRtoInListingMutation,
    useUpdateRtoListingMutation,
    useDeleteRtoListingMutation,
    useAddRtoListingDetailsNoteMutation,
    useGetRtoListingNotesQuery,
    useGetListingRtoDetailsQuery,
    useComposeListingRtoMailMutation,
    useGetListingRtoMailsQuery,

    // ---- TODO ---- //
    useTodoListCountQuery,
    useTicketTodoListQuery,
    useWeeklyFollowUpQuery,
    useWorkplaceTodoListQuery,
    useAppointmentTodoListQuery,
    useRemoveAllTodosMutation,
    useAddAllNewTodosMutation,
    useUpdateTodoStatusMutation,
    useHighPriorityTodoListQuery,
    useCreateWorkplaceTodoMutation,
    useQuarterlyListedIndustriesQuery,
    useBiMonthlyNonPartnerIndustriesQuery,
    useMonthlyPartnerIndustriesFollowUpQuery,
    useManagerTodoAppointmentsQuery,
    useManagerTodoStudentsQuery,

    // ------ NOTES ------ //
    useSubadminNotesQuery,
    useGetNotesQuery,
    useNoteAddMutation,
    useNoteDeleteMutation,
    useUpdateNoteMutation,
    useSubadminNoteStatusChangeMutation,

    // ------ WORKPLACE------ //
    useWorkplaceCountQuery,
    useAgrementSignMutation,
    useViewMoreIndustriesQuery,
    useChangeStatustoSignedMutation,
    useCancelRequestWorkplaceMutation,
    useSubadminWpCancellationRequestsListQuery,
    useGetSubAdminMapSuggestedIndustryDetailQuery,
    useGetSubAdminMapIndustryBranchDetailQuery,
    useGetRtoWpApprovalRequestPendingListQuery,
    useGetRtoWpApprovalRequestApprovedListQuery,
    useGetRtoWpApprovalRequestCountQuery,

    useGetStudentWorkplaceAnswersQuery,
    useGetStudentWorkplaceAvailabilityQuery,
    useGetStudentWorkplacePlacementAnswersQuery,
    useAssignSubadminWorkplaceCourseMutation,
    useStartPlacementMutation,
    useIndustryResponseMutation,
    useAssignToSubAdminMutation,
    useUsAssignSubAdminMutation,
    useCompletePlacementMutation,
    useTerminatePlacementMutation,
    useGetMyStudentsWorkplacesQuery,
    useGetSubAdminWorkplacesQuery,
    useRemoveAppliedIndustryMutation,
    useGetCancelledWorkplacesQuery,
    useGetPlacementStartedWorkplacesQuery,
    useGetSubAdminFilteredWorkplacesQuery,
    useSendInterviewNotificationMutation,
    useForwardWorkplaceToIndustryMutation,
    useAddWorkplaceNoteMutation,
    useRemoveAppliedIndustryFromWorkplaceMutation,
    useGetWorkplaceFoldersQuery,
    useUpdateWorkplaceStatusMutation,
    useCancelWorkplaceStatusMutation,
    useApproveStudentFromIndustryQuery,
    useGetAddedByStudentsWorkplacesQuery,
    useCheckIsIndustryPerformedActionQuery,
    useUpdateWorkplaceIndustryStatusMutation,
    useUpdateWpAppliedIndustryMutation,
    useBlockedStudentsWorkplacesListQuery,
    useSubAdminApplyStudentWorkplaceMutation,
    useAddCustomIndustryMutation,
    useShowExistingIndustriesQuery,
    useAddExistingIndustriesMutation,
    useChangeCustomIndustryStatusMutation,
    useSendMeetingNotificationMutation,
    useContactWorkplaceIndustryMutation,
    useRemoveWorkplaceRequestApprovalMutation,

    // ----- STUDENTS-------//
    useGetSubAdminStudentsQuery,
    useGetSubAdminFlaggedStudentsQuery,
    useUpdateStudentCoursesMutation,
    useGetRtoSubadminStudentsQuery,
    useGetSubAdminSnoozedStudentsQuery,
    useGetSubAdminUrgentStudentsQuery,
    useSubadminCompletedStudentsQuery,
    useGetSubAdminTicketStudentsListQuery,
    useSetNotContactableMutation,
    useStudentRtoWpTypesQuery,
    useCalledStudentMutation,
    useSubAdminStudentCountQuery,
    useProblamaticStudentMutation,
    useCreateAutomatedWpMutation,
    useSendExistingDocumentMutation,
    useEsignDocumentsFoldersListQuery,
    useCheckExistingIndustryRtoDocQuery,
    useUpdateWpIndustryEligibilityMutation,
    useGetStudentCapacityWhenApproveIndustryQuery,
    useSubAdminRequestWorkplaceMutation,
    useStudentActionsApprovalRequestsQuery,
    useSendPasswordToStudentMailMutation,
    useSubAdminFilteredStudentsQuery,
    useSubadminStudentAssignCoursesMutation,
    useGetSubAdminNonContactableStudentsQuery,
    useGetWorkplaceContactedIndustriesQuery,
    useSubadminStudentUnassignCoursesMutation,
    useGetSubAdminStudentWorkplaceQuery,
    useGetStudentCancelledWPQuery,
    useGetSubAdminMyRtoQuery,
    useRerunAutomationMutation,
    useConfirmWpCapacityMutation,
    useConfirmWpCapacityThroughtEmailMutation,
    useAcceptStudentCapacityByIndustryMutation,
    useGetSubAdminStudentCoursesQuery,
    useGetSubAdminStudentDetailQuery,
    useGetSubAdminStudentRtoDetailQuery,
    useGetAllStudentCancelledWorkplacesQuery,
    useUpdateStudentDateMutation,
    useGetWorkplaceRequestLogsQuery,
    useGetWorkplaceIndustryDetailQuery,
    useUpdateStudentApprovalActionsMutation,
    useGetWorkplaceStudentDetailQuery,
    useGetWorkplaceForScheduleQuery,
    useUpdateWorkplaceCourseMutation,
    useGetWorkplaceAppointmentQuery,
    useGetSubAdminStudentWorkplaceDetailQuery,
    useUpdateSubAdminCourseDurationMutation,
    useGetSubAdminMyStudentsQuery,
    useGetUpcomingAppointmentsStudentsQuery,
    useMyStudentsWeeklyCallsListQuery,
    useGetWpTypeByRtoAndCourseQuery,
    useGetSubAdminMyStudentsCallLogQuery,
    useGetRtoCoordinatorStudentsQuery,
    useAssignStudentsToSubAdminMutation,
    useSubAdminRequestIndustryWorkplaceMutation,
    useSubAdminCancelStudentWorkplaceRequestMutation,
    useGetRequiredDocsQuery,
    useGetRequiredFoldersQuery,
    useGetPlacementStartedStudentsQuery,
    useGetRequiredDocsResponseQuery,
    useUploadRequiredDocsMutation,
    useFindByAbnWorkplaceMutation,
    useApplyWorkplaceOnExistingIndustryMutation,
    useAddCustomIndustyForWorkplaceMutation,
    useStudentCoursesQuery,
    useChangeStudentPasswordMutation,
    useUpdateStudentDetailMutation,
    useChangeStudentStatusMutation,
    useGetSubAdminStudentWorkplaceHistoryQuery,
    useChangeStudentCurrentStatusMutation,
    useAddSecondWorkplaceMutation,
    useAddCustomSecondWorkplaceMutation,
    useAddCourseStartEndDateMutation,
    useUpdateCourseStartEndDateMutation,
    useStudentCallLogMutation,
    useGetStudentCallLogQuery,
    useGetSingleStudentCallLogQuery,
    useStudentAnsweredCallMutation,
    useDownloadStudentCSVMutation,
    useFindSuggestedIndustriesQuery,
    useSnoozeStudentMutation,
    useUnSnoozeStudentMutation,
    useSendStudentMssageMutation,
    useGetStudentMessagesListQuery,
    useReleaseStudentLogbookMutation,
    useAddStudentNoteMutation,
    useGetIncompleteSubmissionsForWorkplaceQuery,
    useGetSubAdminIncompleteSubmissionStudentsQuery,
    useGetSubAdminDepartmentCoordinatorsQuery,
    useSubAdminStudentCancelledWorkplacesQuery,
    useSkipWorkplaceMutation,
    useGetIndustryInRadiusWorkplaceEmailsQuery,
    useGetIndustryInRadiusWorkplaceCallLogsQuery,
    useGetFutureIndustryInRadiusWorkplaceEmailsQuery,
    useSkipWorkplaceAndApplyAnotherMutation,
    useSkippedIndustriesListQuery,

    // ---- LOGBOOK ---- //
    useSaveLogbookMutation,
    useGetStudentLogbookQuery,
    useGetStudentLogbookPagesCountQuery,

    // -- COUNT -- //
    useSubadminStatisticsQuery,

    // --- ASSESSMENT EVIDENCE --- //
    useGetAssessmentEvidenceQuery,
    useArchiveAssessmentEvidenceMutation,
    useAssessmentCountQuery,
    useGetAssessmentResponseQuery,
    useGetOtherDocAssessmentResponseQuery,

    useGetAgrementFileQuery,
    useGetArchivedAssessmentResponseQuery,
    useStudentAssessmentCoursesQuery,
    useAddCommentOnAssessmentMutation,
    useGetAssessmentEvidenceDetailQuery,
    useGetArchivedAssessmentEvidenceDetailQuery,
    useSubmitAssessmentEvidenceMutation,
    useMaulallyReopenSubmissionRequestMutation,
    useUploadAssessmentDocsMutation,
    useUploadOtherDocAssessmentDocsMutation,
    useInitiateSigningMutation,
    useGetDocuSignStatusQuery,
    useDownloadAllCourseFilesMutation,
    useDownloadArhiveCourseFilesMutation,
    useArchiveUploadedFileMutation,
    useDeleteAssessmentEvidenceMutation,

    // --- SET SCHEDULE --- //
    useSetScheduleMutation,
    useSetScheduledListQuery,

    // --- SET UNAVAILABILITY -- //
    useAddUnavailabilityMutation,
    useGetUnAvailabilitiesQuery,
    useRemoveUnAvailabilityMutation,

    // --- APOINTMENTS --- //
    useSearchUserQuery,
    useSearchUserByIdQuery,
    useAvailabilityListQuery,
    useSearchSubAdminUsersQuery,
    useUserAvailabilitiesQuery,

    // ---- RTO ---- //
    useSubadminRtoStatisticsCountQuery,
    useSubadminRtoImportStudentsMutation,
    useGetSubAdminRtosFilterListQuery,
    useGetSubAdminRtosQuery,
    useGetSubAdminRTOStatisticsQuery,
    useGetSubAdminRTODetailQuery,
    useGetSubAdminRTOCoursesQuery,
    useGetRTOAssessmentToolsQuery,
    useGetSubAdminRtosStudentsQuery,
    useGetSubAdminRtoAppointmentsQuery,
    useUpdateSubAdminRtoStudentStatusMutation,
    useCreateRtoSubAdminAssessmentToolsMutation,
    useRemoveSubAdminRTOAssessmentToolsMutation,
    useUpdateRtoSubAdminAssessmentToolsMutation,
    useUpdateSubAdminAssessmentToolArchiveMutation,

    // --- SETTING --- //
    useGetSettingDataQuery,
    useSubAdminSettingMutation,

    // --- INDUSTRIES --- //

    useSubadminIndustryStatisticsCountQuery,
    useGetSnoozedIndustryQuery,
    useGetSubadminIndustriesCountQuery,
    useGetSubAdminIndustriesQuery,
    useGetStdProvidedWpAppReqQuery,
    useIndustryProgressQuery,
    useGetRtoCoordinatorsIndustryQuery,
    useUpdatePartnerRemovalRequestStatusMutation,
    useGetFavouriteIndustriesQuery,
    useGetMonthlyCallsListQuery,
    useGetMonthlyCallsIndustriesListQuery,
    useGetSubAdminIndustryStudentsQuery,
    useGetSubAdminIndustriesProfileQuery,
    useGetSubAdminIndustryProfileQuery,
    useAddToFavoriteMutation,
    useAddToPartnerMutation,
    useChangeWPProvidedStatusMutation,
    useRemovePartnerIndustryRequestQuery,
    useRemovalRequestCountQuery,
    useStudentActionsRequestCountQuery,
    useChangeIndustryStatusChangeMutation,
    useIndustryCallLogMutation,
    useGetIndustryCallLogQuery,
    useIndustryAnsweredCallMutation,
    useMakeIndustryHeadquarterMutation,
    useGetIndustryBranchesQuery,
    useRemoveIndustryBranchMutation,
    useChangeIndustryStudentsAcceptingStatusMutation,
    useGetIndustryStudentsScheduleQuery,
    useRequestToAddCoursesToIndustryMutation,
    useConfirmCourseDescriptionMutation,
    useGenerateDescriptionMutation,

    useAddHodNoteMutation,
    useAddPrevCourseDescriptionMutation,
    useGetIndustryRequestedCoursesQuery,
    useGetIndustryCoursesOnAcceptanceQuery,
    useGetRejectedDepartmentIndustryQuery,
    useGetRejectedDepartmentIndustryCountQuery,
    useGetPendingDepartmentIndustryCountQuery,
    useGetPreviousIndustryCoursesQuery,
    useUploadCourseDocForIndustryMutation,
    useGetSectorBasedCapacityQuery,
    useUpdateSectorBaseCapacityMutation,
    useUpdateOldCapacityToSectorBaseMutation,

    // --- REPORTS --- //
    useGetAssignedStudentsReportQuery,
    useGetAssignedWorkplaceReportQuery,
    useGetActiveStudentsReportQuery,
    useGetSubAdminArchivedStudentsReportQuery,
    useGetStudentsCallsReportQuery,
    useGetBookAppointmentsReportQuery,
    useGetSubAdminTerminatedWorkplaceReportQuery,
    useGetSubAdminCompletedWorkplaceReportQuery,
    useGetSubAdminCancelledWorkplaceReportQuery,
    useGetStudentWorkplaceStartedReportQuery,
    useGetStudentWithNoWorkplaceReportQuery,
    useGetSubAdminReportDownloadLinkQuery,
    useGetStudentProvidedWorkplaceReportQuery,

    // ---- VOLUNTEER ---- //
    useGetSubadminVolunteerRequestsQuery,

    // ----- TALENT POOL ----- //
    useGetSubAdminTalentPoolListQuery,
} = subAdminApi

export const SubAdminApi = {
    Count: {
        statistics: useSubadminStatisticsQuery,
    },
    Kpi: {
        deptKpiTargetList: useDeptKpiTargetListQuery,
        deptEmployeeCounts: useDeptEmployeeCountsQuery,
        deptSubadminDetail: useDeptSubadminDetailQuery,
        saveDeptKpiTarget: useSaveDeptKpiTargetMutation,
        verifyDeptSubadmin: useVerifyDeptSubadminMutation,
        deptSubadminReportList: useDeptSubadminReportListQuery,
        deptEmployeeProgressCounts: useDeptEmployeeProgressCountsQuery,
        deptEmployeeProgressByMonth: useDeptEmployeeProgressByMonthQuery,
    },
    SubAdmin: {
        useProfile: useProfileQuery,
        globalSearchList: useGlobalSearchListQuery,
        useSubAdminMapStudentDetail: useGetSubAdminMapStudentDetailQuery,
        useSubAdminMapIndustries: useGetSubAdminMapIndustriesQuery,
        useSubAdminRtosForMap: useGetSubAdminRtosForMapQuery,
        useSubAdminMapStudents: useGetSubAdminMapStudentsQuery,
        useSubAdminStudentSuburbsForMap:
            useGetSubAdminStudentSuburbsForMapQuery,
        useSubadminCourses: useSubadminCoursesQuery,
        useSavedCoordinates: useGetSavedCoordinatesQuery,
        useUpdateProfile: useUpdateSubAdminProfileMutation,
        changeSubAdminUserStatus: useChangeSubAdminUserStatusMutation,
        useSaveCoordinatesForMap: useSaveCoordinatesForMapMutation,
        useImportRtosList: useImportRtosListMutation,
        useRtosStatusChange: useRtosStatusChangeMutation,
        useAddRtoInListing: useAddRtoInListingMutation,
        useUpdateRtoListing: useUpdateRtoListingMutation,
        useDeleteRtoListing: useDeleteRtoListingMutation,
        useAllRtosList: useGetAllRtosListQuery,
        useHodCoordinatorsList: useGetHodCoordinatorsListQuery,
        useCoordinatorsDropDown: useGetCoordinatorsDropDownQuery,
        useDepartmentStudents: useGetDepartmentStudentsQuery,
        useDepartmentPlacementStartedStudents:
            useGetDepartmentPlacementStartedStudentsQuery,
        useDepartmentStudentsCount: useGetDepartmentStudentsCountQuery,
        useDepartmentPendingIndustries: useGetDepartmentPendingIndustriesQuery,
        useDepartmentCoursesRequestList:
            useGetDepartmentCoursesRequestListQuery,
        useDepartmentCourseRequest: useDepartmentCourseRequestMutation,
        useAssignCoordinatorToStudent: useAssignCoordinatorToStudentMutation,
    },
    Todo: {
        todoListCount: useTodoListCountQuery,
        ticketTodoList: useTicketTodoListQuery,
        weeklyFollowUp: useWeeklyFollowUpQuery,
        removeAllTodos: useRemoveAllTodosMutation,
        addAllNewTodos: useAddAllNewTodosMutation,
        workplaceTodoList: useWorkplaceTodoListQuery,
        updateTodoStatus: useUpdateTodoStatusMutation,
        monthlyPartnerIndustriesFollowUp:
            useMonthlyPartnerIndustriesFollowUpQuery,
        appointmentTodoList: useAppointmentTodoListQuery,
        highPriorityTodoList: useHighPriorityTodoListQuery,
        createWorkplaceTodo: useCreateWorkplaceTodoMutation,
        quarterlyListedIndustries: useQuarterlyListedIndustriesQuery,
        biMonthlyNonPartnerIndustries: useBiMonthlyNonPartnerIndustriesQuery,
        useManagerTodoAppointments: useManagerTodoAppointmentsQuery,
        useManagerTodoStudents: useManagerTodoStudentsQuery,
    },
    Notes: {
        useList: useSubadminNotesQuery,
        useCreate: useNoteAddMutation,
        useDelete: useNoteDeleteMutation,
        useStatusChange: useSubadminNoteStatusChangeMutation,
    },

    Student: {
        createAutomatedWp: useCreateAutomatedWpMutation,
        updateWpIndustryEligibility: useUpdateWpIndustryEligibilityMutation,
        addStudentNote: useAddStudentNoteMutation,
        useProblamaticStudent: useProblamaticStudentMutation,
        useCount: useSubAdminStudentCountQuery,
        useList: useGetSubAdminStudentsQuery,
        sendExistingDocument: useSendExistingDocumentMutation,
        esignDocumentsFolders: useEsignDocumentsFoldersListQuery,
        checkExistingIndustryRtoDoc: useCheckExistingIndustryRtoDocQuery,
        useSubAdminFlaggedStudents: useGetSubAdminFlaggedStudentsQuery,
        updateStudentCourses: useUpdateStudentCoursesMutation,
        useRtoSubadminStudentsList: useGetRtoSubadminStudentsQuery,
        useSnoozedStudents: useGetSubAdminSnoozedStudentsQuery,
        useUrgentStudents: useGetSubAdminUrgentStudentsQuery,
        useCompletedStudents: useSubadminCompletedStudentsQuery,
        useSubAdminStudentList: useGetSubAdminTicketStudentsListQuery,
        assignCourse: useSubadminStudentAssignCoursesMutation,
        useMailPassword: useSendPasswordToStudentMailMutation,
        studentActionsApprovalRequests: useStudentActionsApprovalRequestsQuery,
        useGetRtoCoordinatorStudents: useGetRtoCoordinatorStudentsQuery,
        useMysStudentsCallLog: useGetSubAdminMyStudentsCallLogQuery,
        studentWeeklyCallsList: useMyStudentsWeeklyCallsListQuery,
        getUpcomingAppointmentsStudents:
            useGetUpcomingAppointmentsStudentsQuery,
        getWpTypeByRtoAndCourse: useGetWpTypeByRtoAndCourseQuery,
        subadminStudentUnassignCourses:
            useSubadminStudentUnassignCoursesMutation,
        getCancelledWP: useGetStudentCancelledWPQuery,
        useNotContactable: useSetNotContactableMutation,
        studentRtoWpTypes: useStudentRtoWpTypesQuery,
        useCalled: useCalledStudentMutation,
        useCourses: useGetSubAdminStudentCoursesQuery,
        confirmWpCapacity: useConfirmWpCapacityMutation,
        confirmCapacityViaEmail: useConfirmWpCapacityThroughtEmailMutation,
        getStdCapacity: useGetStudentCapacityWhenApproveIndustryQuery,
        acceptStdCapacityBuInd: useAcceptStudentCapacityByIndustryMutation,
        rerunAutomation: useRerunAutomationMutation,
        useUpdateStudentDate: useUpdateStudentDateMutation,
        useChangePassword: useChangeStudentPasswordMutation,
        useUpdateDetail: useUpdateStudentDetailMutation,
        changeStatus: useChangeStudentStatusMutation,
        studentWorkplaceHistory: useGetSubAdminStudentWorkplaceHistoryQuery,
        useStudentCallLog: useStudentCallLogMutation,
        useGetStudentCallLog: useGetStudentCallLogQuery,
        getSingleStudentCallLog: useGetSingleStudentCallLogQuery,
        useAddSecondWorkplace: useAddSecondWorkplaceMutation,
        useDownloadStudentCSV: useDownloadStudentCSVMutation,
        useStudentAnsweredCall: useStudentAnsweredCallMutation,
        changeCurrentStatus: useChangeStudentCurrentStatusMutation,
        useAddCustomWorkplace: useAddCustomSecondWorkplaceMutation,
        addCourseStartEndDate: useAddCourseStartEndDateMutation,
        placementStartedStudents: useGetPlacementStartedStudentsQuery,
        useUpdateCourseStartEndDate: useUpdateCourseStartEndDateMutation,
        wpContactIndustriesList: useGetWorkplaceContactedIndustriesQuery,
        getWorkplaceAppointment: useGetWorkplaceAppointmentQuery,
        useNonContactableStudents: useGetSubAdminNonContactableStudentsQuery,
        useFindSuggestedIndustries: useFindSuggestedIndustriesQuery,
        useSnoozeStudent: useSnoozeStudentMutation,
        useUnSnoozeStudent: useUnSnoozeStudentMutation,
        sendStudentMssage: useSendStudentMssageMutation,
        updateWpCourse: useUpdateWorkplaceCourseMutation,
        studentMessagesList: useGetStudentMessagesListQuery,
        workplaceIndustryDetail: useGetWorkplaceIndustryDetailQuery,
        getWorkplaceIndustryDetail: useGetWorkplaceRequestLogsQuery,
        updateStudentApprovalActions: useUpdateStudentApprovalActionsMutation,
        workplaceStudentDetail: useGetWorkplaceStudentDetailQuery,
        getWorkplaceForSchedule: useGetWorkplaceForScheduleQuery,
        getStudentRtoDetail: useGetSubAdminStudentRtoDetailQuery,
        getAllStudentCancelledWorkplaces:
            useGetAllStudentCancelledWorkplacesQuery,
        releaseStudentLogbook: useReleaseStudentLogbookMutation,
        getIncompleteSubmissionsForWorkplace:
            useGetIncompleteSubmissionsForWorkplaceQuery,
        useIncompleteSubmissionStudents:
            useGetSubAdminIncompleteSubmissionStudentsQuery,
        useDepartmentCoordinators: useGetSubAdminDepartmentCoordinatorsQuery,
        useSubAdminStudentCancelledWorkplaces:
            useSubAdminStudentCancelledWorkplacesQuery,
        skipWorkplace: useSkipWorkplaceMutation,
        useIndustryInRadiusWorkplaceEmails:
            useGetIndustryInRadiusWorkplaceEmailsQuery,
        useIndustryInRadiusWorkplaceCallLogs:
            useGetIndustryInRadiusWorkplaceCallLogsQuery,
        useFutureIndustryInRadiusWorkplaceEmails:
            useGetFutureIndustryInRadiusWorkplaceEmailsQuery,
        skipWpAndApplyAnother: useSkipWorkplaceAndApplyAnotherMutation,
        skippedIndustriesList: useSkippedIndustriesListQuery,
    },
    LogBook: {
        useSaveLogbook: useSaveLogbookMutation,
        useStudentLogbook: useGetStudentLogbookQuery,
        useLogbookPagesCount: useGetStudentLogbookPagesCountQuery,
    },
    Industry: {
        useAddToPartner: useAddToPartnerMutation,
        useIndustryCallLog: useIndustryCallLogMutation,
        useGetIndustryCallLog: useGetIndustryCallLogQuery,
        useGetIndustryBranches: useGetIndustryBranchesQuery,
        useIndustryAnsweredCall: useIndustryAnsweredCallMutation,
        useRemoveIndustryBranch: useRemoveIndustryBranchMutation,
        removalRequestCount: useRemovalRequestCountQuery,
        studentActionsRequestCount: useStudentActionsRequestCountQuery,
        changeIndustryStatusChange: useChangeIndustryStatusChangeMutation,
        changeIndustryAcceptingStatus:
            useChangeIndustryStudentsAcceptingStatusMutation,
        industryProgress: useIndustryProgressQuery,
        useStatusticsCount: useSubadminIndustryStatisticsCountQuery,
        removePartnerIndustryReq: useRemovePartnerIndustryRequestQuery,
        changeWPProvidedStatus: useChangeWPProvidedStatusMutation,
        useMakeIndustryHeadquarter: useMakeIndustryHeadquarterMutation,
        useRtoCoordinatorsIndustries: useGetRtoCoordinatorsIndustryQuery,
        getStdProvidedWpAppReq: useGetStdProvidedWpAppReqQuery,
        updatePartnerRemovalReq: useUpdatePartnerRemovalRequestStatusMutation,
        useIndustryStudentsSchedule: useGetIndustryStudentsScheduleQuery,
        useRequestToAddCoursesToIndustry:
            useRequestToAddCoursesToIndustryMutation,
        getMonthlyCallsList: useGetMonthlyCallsListQuery,
        getMonthlyCallsIndustries: useGetMonthlyCallsIndustriesListQuery,
        useAddPrevCourseDescription: useAddPrevCourseDescriptionMutation,
        addHodNote: useAddHodNoteMutation,
        useIndustryRequestedCourses: useGetIndustryRequestedCoursesQuery,
        useIndustryCoursesOnAcceptance: useGetIndustryCoursesOnAcceptanceQuery,
        useRejectedDepartmentIndustry: useGetRejectedDepartmentIndustryQuery,
        useRejectedDepartmentIndustryCount:
            useGetRejectedDepartmentIndustryCountQuery,
        usePendingDepartmentIndustryCount:
            useGetPendingDepartmentIndustryCountQuery,
        usePreviousIndustryCourses: useGetPreviousIndustryCoursesQuery,
        useSectorBasedCapacity: useGetSectorBasedCapacityQuery,
        uploadCourseDocForIndustry: useUploadCourseDocForIndustryMutation,
        useSectorBaseCapacity: useUpdateSectorBaseCapacityMutation,
        useUpdateOldCapacityToSectorBase:
            useUpdateOldCapacityToSectorBaseMutation,
        useConfirmCourseDescription: useConfirmCourseDescriptionMutation,
        useGenerateDescription: useGenerateDescriptionMutation,
    },
    Rto: {
        useRtoStatsCount: useSubadminRtoStatisticsCountQuery,
        useImportStudentList: useSubadminRtoImportStudentsMutation,
        useRtosFilterList: useGetSubAdminRtosFilterListQuery,
        subadminRtoStatistics: useGetSubAdminRTOStatisticsQuery,
        useAddRtoListingDetailsNote: useAddRtoListingDetailsNoteMutation,
        useGetRtoListingNotes: useGetRtoListingNotesQuery,
        useListingRtoDetails: useGetListingRtoDetailsQuery,
        useComposeListingRtoMail: useComposeListingRtoMailMutation,
        useListingRtoMails: useGetListingRtoMailsQuery,
    },
    Workplace: {
        count: useWorkplaceCountQuery,
        useStudentWorkplaceAnswers: useGetStudentWorkplaceAnswersQuery,
        useWorkplaceAvailability: useGetStudentWorkplaceAvailabilityQuery,
        useStudentPlacementAnswers: useGetStudentWorkplacePlacementAnswersQuery,
        useViewMoreIndustries: useViewMoreIndustriesQuery,
        useChangeStatustoSigned: useChangeStatustoSignedMutation,
        assignCourse: useAssignSubadminWorkplaceCourseMutation,
        AgreementSign: useAgrementSignMutation,
        removeAppliedIndustry: useRemoveAppliedIndustryMutation,
        removeAppliedIndustryFromWorkplace:
            useRemoveAppliedIndustryFromWorkplaceMutation,
        useStartPlacementMutation,
        useIndustryResponseMutation,
        useAssignToSubAdminMutation,

        useUsAssignSubAdminMutation,
        useCompletePlacementMutation,
        useTerminatePlacementMutation,
        useGetMyStudentsWorkplacesQuery,
        usePlacementStartedWorkplaces: useGetPlacementStartedWorkplacesQuery,
        useGetSubAdminWorkplacesQuery,
        useGetCancelledWorkplacesQuery,
        useGetSubAdminFilteredWorkplacesQuery,
        useSendInterviewNotificationMutation,
        useForwardWorkplaceToIndustryMutation,
        useAddWorkplaceNoteMutation,
        useGetWorkplaceFoldersQuery,
        useUpdateWorkplaceStatusMutation,
        useCancelWorkplaceStatusMutation,
        useGetAddedByStudentsWorkplacesQuery,
        approveStudentFromIndustry: useApproveStudentFromIndustryQuery,
        updateWpIndustryStatus: useUpdateWorkplaceIndustryStatusMutation,
        checkIsIndustryPerformedAction: useCheckIsIndustryPerformedActionQuery,

        useSubAdminApplyStudentWorkplaceMutation,
        useAddCustomIndustryMutation,
        useShowExistingIndustriesQuery,
        useAddExistingIndustriesMutation,
        useChangeCustomIndustryStatusMutation,
        useCancelRequestWP: useCancelRequestWorkplaceMutation,
        blockedStudentsWpList: useBlockedStudentsWorkplacesListQuery,
        updateWpAppliedIndustry: useUpdateWpAppliedIndustryMutation,
        subadminCancelationRequest: useSubadminWpCancellationRequestsListQuery,
        useSendMeetingNotification: useSendMeetingNotificationMutation,
        contactWorkplaceIndustry: useContactWorkplaceIndustryMutation,
        removeWPApprovalReq: useRemoveWorkplaceRequestApprovalMutation,
        useSubAdminMapSuggestedIndustryDetail:
            useGetSubAdminMapSuggestedIndustryDetailQuery,
        useSubAdminMapIndustryBranchDetail:
            useGetSubAdminMapIndustryBranchDetailQuery,
        useMapIndustriesInRadiusCount: useGetMapIndustriesInRadiusCountQuery,
        useWorkplaceCourseIndustries: useGetWorkplaceCourseIndustriesQuery,
        useWorkplaceListedIndustries: useGetWorkplaceListedIndustriesQuery,
        changeWpReqStatus: useChangeWorkplaceApprovalReqStatusMutation,
        placementAndInsuranceDocNote:
            useGetWarningPlacementAndInsuranceDocNoteQuery,
        useRtoWpApprovalRequestPendingList:
            useGetRtoWpApprovalRequestPendingListQuery,
        useRtoWpApprovalRequestApprovedList:
            useGetRtoWpApprovalRequestApprovedListQuery,
        useRtoWpApprovalRequestCount: useGetRtoWpApprovalRequestCountQuery,
    },

    Courses: {
        useStudentCourses: useStudentCoursesQuery,
    },

    Docs: {
        useRequiredDocs: useGetRequiredDocsQuery,
        useRequiredFolders: useGetRequiredFoldersQuery,
        useRequiredDocsResponse: useGetRequiredDocsResponseQuery,
    },
    AssessmentEvidence: {
        uploadDocs: useUploadAssessmentDocsMutation,
        getOtherDocAssessment: useGetOtherDocAssessmentResponseQuery,
        uploadOtherDocs: useUploadOtherDocAssessmentDocsMutation,
        useInitiateSigning: useInitiateSigningMutation,
        useDocuSignStatus: useGetDocuSignStatusQuery,
        archiveUploadedFile: useArchiveUploadedFileMutation,
        deleteAssessmentEvidence: useDeleteAssessmentEvidenceMutation,
        downloadFiles: useDownloadAllCourseFilesMutation,
        downloadArchiveFiles: useDownloadArhiveCourseFilesMutation,
        useArchiveAssessmentEvidence: useArchiveAssessmentEvidenceMutation,
    },
    Reports: {
        useAssignedStudents: useGetAssignedStudentsReportQuery,
        useAssignedWorkplace: useGetAssignedWorkplaceReportQuery,
        useActiveStudentsReport: useGetActiveStudentsReportQuery,
        useArchiveStudentsReport: useGetSubAdminArchivedStudentsReportQuery,
        useStudentsCallsReport: useGetStudentsCallsReportQuery,
        useBookAppointmentsReport: useGetBookAppointmentsReportQuery,
        useTerminatedWorkplaceReport:
            useGetSubAdminTerminatedWorkplaceReportQuery,
        useCompletedWorkplaceReport:
            useGetSubAdminCompletedWorkplaceReportQuery,
        useCancelledWorkplaceReport:
            useGetSubAdminCancelledWorkplaceReportQuery,
        useStudentWorkplaceStartedReport:
            useGetStudentWorkplaceStartedReportQuery,
        useStudentWithNoWorkplaceReport:
            useGetStudentWithNoWorkplaceReportQuery,
        useDownloadLink: useGetSubAdminReportDownloadLinkQuery,
        useStudentProvidedWorkplaceReport:
            useGetStudentProvidedWorkplaceReportQuery,
    },
    Volunteer: {
        useVolunteerRequests: useGetSubadminVolunteerRequestsQuery,
    },
    TalentPool: {
        useTalentPoolList: useGetSubAdminTalentPoolListQuery,
    },
}
