import { RtoV2Api } from '@redux'
import { useAppSelector } from '@redux/hooks'
import { StudentCard } from './StudentCard'
import { EmptyData, LoadingAnimation, TechnicalError } from '@components'

export function StudentsList() {
    const industry = useAppSelector((state) => state.industry)
    const students = RtoV2Api.Industries.industryStudentsList(
        {
            sectorId: industry?.activeSector ?? 0,
            industryId: industry?.industryDetail?.id ?? 0,
            params: {
                search: '',
                skip: 0,
                limit: 10,
            },
        },
        {
            skip: !industry?.activeSector || !industry?.industryDetail?.id,
        }
    )

    const studentss = {
        data: {
            data: [
                {
                    id: 359,
                    isActive: true,
                    createdAt: '2025-04-29T04:13:26.357Z',
                    updatedAt: '2025-05-29T02:00:00.089Z',
                    skiltrakId: null,
                    familyName: 'asdasd',
                    studentId: '8638',
                    phone: '+1234567002',
                    age: '26-36',
                    gender: 'M',
                    isInternational: true,
                    enrollmentId: null,
                    emergencyPerson: 'asdasd',
                    emergencyPersonPhone: '2342342',
                    addressLine1:
                        'Poplar Street, Surry Hills City of Sydney, NSW, Australia',
                    addressLine2: '',
                    zipCode: '2010',
                    suburb: 'N/A',
                    state: 'New South Wales',
                    location: '-33.8783512,151.2128038',
                    location2: null,
                    expiryDate: '2027-12-23T19:00:00.000Z',
                    oldExpiry: null,
                    batch: 'khjgjvokok',
                    studentStatus: 'active',
                    changeStatus: null,
                    assignToCoordinatorDate: '2025-05-01T02:13:16.897Z',
                    nonContactable: false,
                    nonContactableAt: null,
                    called: false,
                    calledAtt: null,
                    cv: null,
                    courseDescription: null,
                    rtoInfo: null,
                    inCompleteSubmission: false,
                    inCompleteSubmissionDate: null,
                    placementType: 'FLEXIBLE',
                    blockStartDate: null,
                    blockEndDate: null,
                    isHighPriority: false,
                    AutoHighPriority: false,
                    isSelfRegistered: false,
                    highPriorityAt: null,
                    hasIssue: false,
                    hasPaid: false,
                    isReported: false,
                    isAddressUpdated: true,
                    isSnoozed: false,
                    autoCreateTalentPoolProfile: false,
                    snoozedDate: null,
                    snoozedAt: '2025-05-08T05:43:44.463Z',
                    isTransferred: false,
                    user: {
                        id: 673,
                        isActive: true,
                        createdAt: '2025-04-29T04:13:26.290Z',
                        updatedAt: '2025-05-08T03:53:57.175Z',
                        skiltrakId: null,
                        name: 'Willow Hall',
                        messageCount: null,
                        email: 'willow.hall2@example.com',
                        statusChange: null,
                        statusChangeHistory: null,
                        role: 'student',
                        status: 'approved',
                        socketId: null,
                        avatar: null,
                        temporaryBlock: false,
                        after_hours_access: true,
                        refreshToken:
                            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiV2lsbG93IEhhbGwiLCJyb2xlIjoic3R1ZGVudCIsImlkIjo2NzMsImVtYWlsIjoid2lsbG93LmhhbGwyQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiYXBwcm92ZWQiLCJhdmF0YXIiOm51bGwsImlhdCI6MTc0NjY3NTk1N30.nw5KdWn_c041c6OKGCtPEQ43sTO9CXfY5CMoUuYODkE',
                        notificationViaSms: null,
                        notificationViaEmail: null,
                        stripeCustomerId: null,
                        isEmailVerified: false,
                    },
                    workplace: [
                        {
                            id: 770,
                            isActive: true,
                            createdAt: '2025-05-05T08:08:17.766Z',
                            updatedAt: '2025-05-08T03:54:36.113Z',
                            skiltrakId: null,
                            currentWork: null,
                            currentRadius: 5,
                            currentStatus: 'AgreementSigned',
                            currentQualification: null,
                            haveTransport: false,
                            isCancelled: false,
                            autoCompleted: false,
                            approvalStatus: 'pending',
                            haveDrivingLicense: false,
                            industryStatus: 'approved',
                            reasonForRejection: null,
                            preferableLocation:
                                'Poplar Street, Surry Hills City of Sydney, NSW, Australia',
                            cancelledBy: null,
                            cancelledAt: null,
                            assignedAt: '2025-05-05T08:08:17.812Z',
                            interviewDate: '2025-05-05T08:08:17.869Z',
                            appointmentDate: '2025-05-08T02:55:57.181Z',
                            status: 'pending',
                            lastEmailSentDate: null,
                            isLogBookReleased: false,
                            studentProvidedWorkplace: false,
                            byExistingAbn: false,
                            industries: [
                                {
                                    id: 749,
                                    isActive: true,
                                    createdAt: '2025-05-05T08:09:47.150Z',
                                    updatedAt: '2025-06-16T08:08:18.860Z',
                                    applied: true,
                                    distance: null,
                                    accepted: true,
                                    isAutomated: false,
                                    appliedDate: '2025-05-05T08:09:47.149Z',
                                    industryCheck: false,
                                    industryCheckDate: null,
                                    caseOfficerAssigned: true,
                                    caseOfficerAssignedDate:
                                        '2025-06-16T08:08:18.847Z',
                                    interview: true,
                                    interviewDate: '2025-05-08T02:55:57.168Z',
                                    awaitingWorkplaceResponse: true,
                                    awaitingWorkplaceResponseDate:
                                        '2025-06-16T08:08:18.847Z',
                                    appointmentBooked: true,
                                    appointmentBookedDate:
                                        '2025-05-08T02:55:57.168Z',
                                    awaitingAgreementSigned: true,
                                    awaitingAgreementSignedDate:
                                        '2025-06-16T08:08:18.856Z',
                                    AgreementSigned: true,
                                    AgreementSignedDate:
                                        '2025-05-08T03:54:36.167Z',
                                    cancelled: false,
                                    cancelledDate: null,
                                    terminated: false,
                                    terminatedDate: null,
                                    isCompleted: false,
                                    isCompletedDate: null,
                                    placementStarted: false,
                                    placementStartedDate: null,
                                    industryResponse: 'approved',
                                    industryResponseDate:
                                        '2025-06-16T08:08:18.847Z',
                                    industry: {
                                        id: 200,
                                        isActive: true,
                                        createdAt: '2025-02-19T02:14:19.885Z',
                                        updatedAt: '2025-12-14T12:44:27.346Z',
                                        skiltrakId: null,
                                        businessName: null,
                                        abn: '32423455567',
                                        phoneNumber: '  ',
                                        website: '',
                                        createdByStudent: false,
                                        profileCompletionPercentage: '72.73',
                                        missingAttributes: [],
                                        contactPerson: 'dsfsdfdsf asfsf',
                                        contactPersonNumber: '  ',
                                        isPartner: true,
                                        isAddressUpdated: true,
                                        channel: 'FutureIndustry',
                                        placementStatus: null,
                                        isPartnerAt: '2025-05-29T02:54:06.349Z',
                                        studentCapacity: 0,
                                        enrolledStudents: 4,
                                        addressLine1:
                                            '191 Morialta St, Adelaide SA 5000, Australia',
                                        isSnoozed: false,
                                        isPremium: false,
                                        snoozedDate: null,
                                        snoozedAt: null,
                                        addressLine2: null,
                                        zipCode: '5000',
                                        serviceOffered: null,
                                        suburb: 'Adelaide',
                                        state: 'South Australia',
                                        location: '-34.9277029,138.5986704',
                                        isContacted: false,
                                        isHiring: false,
                                        doNotDisturb: false,
                                        lastContactedAt:
                                            '2025-09-02T07:58:15.410Z',
                                        isRtoAssociated: false,
                                        isAllowedToShare: false,
                                    },
                                },
                            ],
                        },
                    ],
                },
                {
                    id: 365,
                    isActive: true,
                    createdAt: '2025-05-06T03:54:56.567Z',
                    updatedAt: '2025-05-08T07:00:00.031Z',
                    skiltrakId: null,
                    familyName: 'fsdfsd',
                    studentId: '2',
                    phone: '12',
                    age: '26-36',
                    gender: 'M',
                    isInternational: true,
                    enrollmentId: null,
                    emergencyPerson: 'dsfsdfsd',
                    emergencyPersonPhone: '242343',
                    addressLine1:
                        'Melbourne Street, North Adelaide SA, Australia',
                    addressLine2: '',
                    zipCode: '5006',
                    suburb: 'N/A',
                    state: 'South Australia',
                    location: '-34.9073989,138.6067228',
                    location2: null,
                    expiryDate: '2026-01-07T19:00:00.000Z',
                    oldExpiry: null,
                    batch: 'dsfsdf',
                    studentStatus: 'active',
                    changeStatus: null,
                    assignToCoordinatorDate: '2025-05-06T03:54:56.617Z',
                    nonContactable: false,
                    nonContactableAt: null,
                    called: false,
                    calledAtt: null,
                    cv: null,
                    courseDescription: null,
                    rtoInfo: null,
                    inCompleteSubmission: true,
                    inCompleteSubmissionDate: '2025-05-08T07:00:00.030Z',
                    placementType: 'FLEXIBLE',
                    blockStartDate: null,
                    blockEndDate: null,
                    isHighPriority: false,
                    AutoHighPriority: false,
                    isSelfRegistered: false,
                    highPriorityAt: null,
                    hasIssue: false,
                    hasPaid: false,
                    isReported: false,
                    isAddressUpdated: true,
                    isSnoozed: false,
                    autoCreateTalentPoolProfile: false,
                    snoozedDate: null,
                    snoozedAt: null,
                    isTransferred: false,
                    user: {
                        id: 680,
                        isActive: true,
                        createdAt: '2025-05-06T03:54:56.557Z',
                        updatedAt: '2025-08-22T04:42:25.400Z',
                        skiltrakId: null,
                        name: 'qw',
                        messageCount: null,
                        email: 'b@gmail.com',
                        statusChange: null,
                        statusChangeHistory: null,
                        role: 'student',
                        status: 'approved',
                        socketId: null,
                        avatar: null,
                        temporaryBlock: false,
                        after_hours_access: true,
                        refreshToken:
                            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicXciLCJyb2xlIjoic3R1ZGVudCIsImlkIjo2ODAsImVtYWlsIjoiYkBnbWFpbC5jb20iLCJzdGF0dXMiOiJhcHByb3ZlZCIsImF2YXRhciI6bnVsbCwiaWF0IjoxNzU1ODM3NzQ1fQ.03_1POVH-LZiLpjGK4PpMC_Gbd3jpA1X7FSW5UFVj08',
                        notificationViaSms: null,
                        notificationViaEmail: null,
                        stripeCustomerId: null,
                        isEmailVerified: false,
                    },
                    workplace: [
                        {
                            id: 771,
                            isActive: true,
                            createdAt: '2025-05-06T06:56:51.602Z',
                            updatedAt: '2025-06-16T08:08:06.490Z',
                            skiltrakId: null,
                            currentWork: null,
                            currentRadius: 5,
                            currentStatus: 'completed',
                            currentQualification: null,
                            haveTransport: false,
                            isCancelled: false,
                            autoCompleted: true,
                            approvalStatus: 'approved',
                            haveDrivingLicense: false,
                            industryStatus: 'approved',
                            reasonForRejection: null,
                            preferableLocation:
                                'Melbourne Street, North Adelaide SA, Australia',
                            cancelledBy: null,
                            cancelledAt: null,
                            assignedAt: '2025-05-06T06:56:51.647Z',
                            interviewDate: '2025-05-06T06:56:51.699Z',
                            appointmentDate: '2025-05-06T07:01:43.175Z',
                            status: 'pending',
                            lastEmailSentDate: null,
                            isLogBookReleased: true,
                            studentProvidedWorkplace: false,
                            byExistingAbn: false,
                            industries: [
                                {
                                    id: 751,
                                    isActive: true,
                                    createdAt: '2025-05-06T06:59:58.912Z',
                                    updatedAt: '2025-05-09T04:51:00.305Z',
                                    applied: true,
                                    distance: null,
                                    accepted: true,
                                    isAutomated: false,
                                    appliedDate: '2025-05-06T06:59:58.912Z',
                                    industryCheck: false,
                                    industryCheckDate: null,
                                    caseOfficerAssigned: true,
                                    caseOfficerAssignedDate:
                                        '2025-05-06T07:06:31.481Z',
                                    interview: true,
                                    interviewDate: '2025-05-06T07:01:43.164Z',
                                    awaitingWorkplaceResponse: true,
                                    awaitingWorkplaceResponseDate:
                                        '2025-05-06T07:06:31.481Z',
                                    appointmentBooked: true,
                                    appointmentBookedDate:
                                        '2025-05-06T07:01:43.164Z',
                                    awaitingAgreementSigned: true,
                                    awaitingAgreementSignedDate:
                                        '2025-05-08T02:00:26.580Z',
                                    AgreementSigned: true,
                                    AgreementSignedDate:
                                        '2025-05-08T02:00:26.580Z',
                                    cancelled: false,
                                    cancelledDate: null,
                                    terminated: false,
                                    terminatedDate: null,
                                    isCompleted: true,
                                    isCompletedDate: '2025-05-09T04:51:00.299Z',
                                    placementStarted: false,
                                    placementStartedDate:
                                        '2025-05-08T02:02:23.835Z',
                                    industryResponse: 'approved',
                                    industryResponseDate:
                                        '2025-05-06T07:06:31.481Z',
                                    industry: {
                                        id: 200,
                                        isActive: true,
                                        createdAt: '2025-02-19T02:14:19.885Z',
                                        updatedAt: '2025-12-14T12:44:27.346Z',
                                        skiltrakId: null,
                                        businessName: null,
                                        abn: '32423455567',
                                        phoneNumber: '  ',
                                        website: '',
                                        createdByStudent: false,
                                        profileCompletionPercentage: '72.73',
                                        missingAttributes: [],
                                        contactPerson: 'dsfsdfdsf asfsf',
                                        contactPersonNumber: '  ',
                                        isPartner: true,
                                        isAddressUpdated: true,
                                        channel: 'FutureIndustry',
                                        placementStatus: null,
                                        isPartnerAt: '2025-05-29T02:54:06.349Z',
                                        studentCapacity: 0,
                                        enrolledStudents: 4,
                                        addressLine1:
                                            '191 Morialta St, Adelaide SA 5000, Australia',
                                        isSnoozed: false,
                                        isPremium: false,
                                        snoozedDate: null,
                                        snoozedAt: null,
                                        addressLine2: null,
                                        zipCode: '5000',
                                        serviceOffered: null,
                                        suburb: 'Adelaide',
                                        state: 'South Australia',
                                        location: '-34.9277029,138.5986704',
                                        isContacted: false,
                                        isHiring: false,
                                        doNotDisturb: false,
                                        lastContactedAt:
                                            '2025-09-02T07:58:15.410Z',
                                        isRtoAssociated: false,
                                        isAllowedToShare: false,
                                    },
                                },
                            ],
                        },
                    ],
                },
                {
                    id: 327,
                    isActive: true,
                    createdAt: '2025-04-29T04:04:51.937Z',
                    updatedAt: '2025-10-17T02:11:37.841Z',
                    skiltrakId: null,
                    familyName: 'werwer',
                    studentId: '36040',
                    phone: '+1234567049',
                    age: '26-36',
                    gender: 'M',
                    isInternational: false,
                    enrollmentId: null,
                    emergencyPerson: 'asdasd',
                    emergencyPersonPhone: '234234',
                    addressLine1: 'Victoria Square, Adelaide SA, Australia',
                    addressLine2: '',
                    zipCode: '5000',
                    suburb: 'N/A',
                    state: 'South Australia',
                    location: '-34.928133,138.5999216',
                    location2: null,
                    expiryDate: '2026-05-20T19:00:00.000Z',
                    oldExpiry: null,
                    batch: '12345',
                    studentStatus: 'active',
                    changeStatus: null,
                    assignToCoordinatorDate: null,
                    nonContactable: false,
                    nonContactableAt: '2025-08-18T04:58:32.188Z',
                    called: false,
                    calledAtt: null,
                    cv: null,
                    courseDescription: null,
                    rtoInfo: null,
                    inCompleteSubmission: false,
                    inCompleteSubmissionDate: null,
                    placementType: 'FLEXIBLE',
                    blockStartDate: null,
                    blockEndDate: null,
                    isHighPriority: true,
                    AutoHighPriority: false,
                    isSelfRegistered: false,
                    highPriorityAt: null,
                    hasIssue: false,
                    hasPaid: false,
                    isReported: false,
                    isAddressUpdated: true,
                    isSnoozed: false,
                    autoCreateTalentPoolProfile: false,
                    snoozedDate: null,
                    snoozedAt: null,
                    isTransferred: false,
                    user: {
                        id: 641,
                        isActive: true,
                        createdAt: '2025-04-29T04:04:51.919Z',
                        updatedAt: '2025-10-24T06:54:08.524Z',
                        skiltrakId: null,
                        name: 'Clara Gallagher',
                        messageCount: null,
                        email: 'Shaheer.alam1923@gmail.com',
                        statusChange: null,
                        statusChangeHistory: null,
                        role: 'student',
                        status: 'approved',
                        socketId: null,
                        avatar: null,
                        temporaryBlock: false,
                        after_hours_access: true,
                        refreshToken:
                            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2xhcmEgR2FsbGFnaGVyIiwicm9sZSI6InN0dWRlbnQiLCJpZCI6NjQxLCJlbWFpbCI6IlNoYWhlZXIuYWxhbTE5MjNAZ21haWwuY29tIiwic3RhdHVzIjoiYXBwcm92ZWQiLCJhdmF0YXIiOm51bGwsImlhdCI6MTc2MTI4ODg0OH0.t_A9GGfUjZ9XrcfXn_gIaSPBwzwHgGVca_jj9xXgnHo',
                        notificationViaSms: null,
                        notificationViaEmail: null,
                        stripeCustomerId: null,
                        isEmailVerified: false,
                    },
                    workplace: [
                        {
                            id: 860,
                            isActive: true,
                            createdAt: '2025-07-09T08:11:05.766Z',
                            updatedAt: '2025-10-24T06:26:03.922Z',
                            skiltrakId: null,
                            currentWork: null,
                            currentRadius: 90,
                            currentStatus: 'awaitingAgreementSigned',
                            currentQualification: null,
                            haveTransport: false,
                            isCancelled: false,
                            autoCompleted: false,
                            approvalStatus: 'approved',
                            haveDrivingLicense: false,
                            industryStatus: 'approved',
                            reasonForRejection: null,
                            preferableLocation:
                                'Birch Street, Kingston TAS, Australia',
                            cancelledBy: null,
                            cancelledAt: null,
                            assignedAt: '2025-07-09T08:11:05.813Z',
                            interviewDate: '2025-09-29T08:58:27.817Z',
                            appointmentDate: '2025-10-01T04:43:42.266Z',
                            status: 'pending',
                            lastEmailSentDate: null,
                            isLogBookReleased: false,
                            studentProvidedWorkplace: false,
                            byExistingAbn: false,
                            industries: [
                                {
                                    id: 837,
                                    isActive: true,
                                    createdAt: '2025-10-01T04:43:25.335Z',
                                    updatedAt: '2025-10-01T04:43:42.277Z',
                                    applied: true,
                                    distance: null,
                                    accepted: false,
                                    isAutomated: false,
                                    appliedDate: '2025-10-01T04:43:25.334Z',
                                    industryCheck: false,
                                    industryCheckDate: null,
                                    caseOfficerAssigned: false,
                                    caseOfficerAssignedDate: null,
                                    interview: true,
                                    interviewDate: '2025-10-01T04:43:42.274Z',
                                    awaitingWorkplaceResponse: true,
                                    awaitingWorkplaceResponseDate:
                                        '2025-10-01T04:43:25.341Z',
                                    appointmentBooked: true,
                                    appointmentBookedDate:
                                        '2025-10-01T04:43:42.274Z',
                                    awaitingAgreementSigned: false,
                                    awaitingAgreementSignedDate: null,
                                    AgreementSigned: false,
                                    AgreementSignedDate: null,
                                    cancelled: false,
                                    cancelledDate: null,
                                    terminated: false,
                                    terminatedDate: null,
                                    isCompleted: false,
                                    isCompletedDate: null,
                                    placementStarted: false,
                                    placementStartedDate: null,
                                    industryResponse: 'approved',
                                    industryResponseDate:
                                        '2025-10-01T04:43:42.269Z',
                                    industry: {
                                        id: 200,
                                        isActive: true,
                                        createdAt: '2025-02-19T02:14:19.885Z',
                                        updatedAt: '2025-12-14T12:44:27.346Z',
                                        skiltrakId: null,
                                        businessName: null,
                                        abn: '32423455567',
                                        phoneNumber: '  ',
                                        website: '',
                                        createdByStudent: false,
                                        profileCompletionPercentage: '72.73',
                                        missingAttributes: [],
                                        contactPerson: 'dsfsdfdsf asfsf',
                                        contactPersonNumber: '  ',
                                        isPartner: true,
                                        isAddressUpdated: true,
                                        channel: 'FutureIndustry',
                                        placementStatus: null,
                                        isPartnerAt: '2025-05-29T02:54:06.349Z',
                                        studentCapacity: 0,
                                        enrolledStudents: 4,
                                        addressLine1:
                                            '191 Morialta St, Adelaide SA 5000, Australia',
                                        isSnoozed: false,
                                        isPremium: false,
                                        snoozedDate: null,
                                        snoozedAt: null,
                                        addressLine2: null,
                                        zipCode: '5000',
                                        serviceOffered: null,
                                        suburb: 'Adelaide',
                                        state: 'South Australia',
                                        location: '-34.9277029,138.5986704',
                                        isContacted: false,
                                        isHiring: false,
                                        doNotDisturb: false,
                                        lastContactedAt:
                                            '2025-09-02T07:58:15.410Z',
                                        isRtoAssociated: false,
                                        isAllowedToShare: false,
                                    },
                                },
                            ],
                        },
                    ],
                },
            ],
        },
    }

    console.log({ students })
    return (
        <div className="space-y-2">
            {students?.isError ? <TechnicalError /> : null}
            {students?.isLoading ? (
                <LoadingAnimation />
            ) : students?.isSuccess &&
              students?.data?.data &&
              students?.data?.data?.length > 0 ? (
                students?.data?.data?.map((student) => (
                    <StudentCard key={student.id} student={student} />
                ))
            ) : students?.isSuccess ? (
                <EmptyData
                    title="No Students"
                    description="No students found"
                    height="50vh"
                />
            ) : null}
        </div>
    )
}
