import { useDraggable } from '@dnd-kit/core'
import { CSS } from '@dnd-kit/utilities'
import { RubberBand } from './RubberBand'
import { useState } from 'react'

export const DraggableTab = ({
    item,
    onResize,
    onResized,
    onItemSelected,
    onRemove,
}: any) => {
    const { attributes, listeners, setNodeRef, transform }: any = useDraggable({
        id: `input-tab-${item.id}`,
        data: { ...item, dataLabel: 'autogenerated-datalabel' },
    })

    const style = {
        ...(transform
            ? {
                  transform: CSS.Translate.toString({
                      x: transform.x + item.location?.x,
                      y: transform.y + item.location?.y,
                      scaleX: transform?.scaleX,
                      scaleY: transform?.scaleY,
                  }),
              }
            : {}),
    }

    return (
        <g
            data-view-name="tab"
            data-view-id=""
            cursor={'grab'}
            ref={setNodeRef}
            className="outline-none z-50"
            {...(item.moving
                ? { style: { ...style } }
                : {
                      transform: `matrix(1 0 0 1 ${item.location.x} ${item.location.y})`,
                  })}
            onMouseDown={(e: any) => {
                onItemSelected(item, !item.selected)
            }}
            {...listeners}
            onKeyDown={(e: any) => {
                var key = e.which || e.keyCode || e.charCode
                if (key == 8 || key == 46) {
                    onRemove(item)
                }

                listeners.onKeyDown(e)
            }}
            {...attributes}
        >
            <rect
                width={item.size?.width}
                height={item.size?.height}
                // fill="#F7910F"
                fill={item.data?.color}
                fillOpacity="0.25"
            />
            <rect
                x="0.5"
                y="0.5"
                width={item.size?.width}
                height={item.size?.height}
                // stroke="#A9650E"
                stroke={item.data?.color}
                fillOpacity={'0'}
            />
            <text className="text-[13px]" x="6" y="18" fill={item.data?.color}>
                {item.data?.placeholder || 'Text'}
            </text>

            {item.selected && (
                <RubberBand
                    item={item}
                    onResize={onResize}
                    onResized={onResized}
                />
            )}
        </g>
    )
}
