import { useDraggable } from '@dnd-kit/core'
import { CSS } from '@dnd-kit/utilities'
import { RubberBand } from './RubberBand'
import { useEffect, useState } from 'react'
import { TextInput } from '@components/inputs'
import { FieldsTypeEnum } from './SidebarData'

export const DraggableTab = ({
    item,
    onResize,
    onResized,
    onItemSelected,
    onRemove,
    tabsError,
}: any) => {
    const { attributes, listeners, setNodeRef, transform }: any = useDraggable({
        id: `input-tab-${item.id}`,
        data: { ...item, dataLabel: 'autogenerated-datalabel' },
    })

    const [isTabError, setIsTabError] = useState(false)

    useEffect(() => {
        if (
            tabsError &&
            tabsError?.map((tab: any) => tab.id).includes(item?.id)
        ) {
            setIsTabError(true)
        }
        if (item?.data?.role) {
            setIsTabError(false)
        }
    }, [item?.data?.role, tabsError])

    const style = {
        ...(transform
            ? {
                  transform: CSS.Translate.toString({
                      x: transform.x + item.location?.x,
                      y: transform.y + item.location?.y,
                      scaleX: transform?.scaleX,
                      scaleY: transform?.scaleY,
                  }),
              }
            : {}),
    }
    console.log({ item })
    return (
        <g
            id={item?.id}
            data-view-name="tab"
            data-view-id=""
            cursor={'grab'}
            ref={setNodeRef}
            className="outline-none z-50"
            {...(item.moving
                ? { style: { ...style } }
                : {
                      transform: `matrix(1 0 0 1 ${item.location.x} ${item.location.y})`,
                  })}
            onMouseDown={(e: any) => {
                onItemSelected(item, !item.selected, true)
            }}
            onMouseUp={(e: any) => {
                onItemSelected(item, item.selected, false)
            }}
            {...listeners}
            onKeyDown={(e: any) => {
                var key = e.which || e.keyCode || e.charCode
                if (key == 8 || key == 46) {
                    onRemove(item)
                }

                listeners.onKeyDown(e)
            }}
            {...attributes}
        >
            {item?.data?.type === FieldsTypeEnum.Checkbox ? (
                <>
                    <rect
                        x="0"
                        y="0"
                        width="12"
                        height="12"
                        fill={
                            !item?.data?.role && isTabError
                                ? 'red'
                                : item.data?.color
                        }
                        stroke="black"
                        strokeWidth="1"
                        // onClick={handleCheckboxChange}
                    />
                    <text x="2" y="9" className="text-[10px]" fill={'white'}>
                        ✔
                    </text>
                </>
            ) : (
                <>
                    {!item?.data?.role && isTabError ? (
                        <>
                            <rect
                                x="0" // Adjust the x-coordinate to move the background closer to the text
                                y="-9" // Adjust the y-coordinate to move the background closer to the text
                                width={item.size?.width} // Adjust the width to reduce the size of the background
                                height="8" // Adjust the height to reduce the size of the background
                                fill="white" // Replace 'yellow' with the desired background color
                                fillOpacity="1"
                            />
                            <text
                                x="2"
                                y="-2"
                                className="text-[7px] "
                                fill={'red'}
                            >
                                Please Select the role
                            </text>
                        </>
                    ) : (
                        item?.data?.isCustom && (
                            <text
                                style={{
                                    backgroundColor: 'yellow',
                                    fontSize: '7px',
                                    color: item.data?.color,
                                }}
                                className="uppercase"
                                x="2"
                                y="-2"
                                // fill={item.data?.color}
                            >
                                {item?.data?.role}
                            </text>
                        )
                    )}
                    <rect
                        width={item.size?.width}
                        height={item.size?.height}
                        // fill="#F7910F"
                        fill={
                            !item?.data?.role && isTabError
                                ? 'red'
                                : item.data?.color
                        }
                        fillOpacity="0.4"
                    />
                    <rect
                        x="0.5"
                        y="0.5"
                        width={item.size?.width}
                        height={item.size?.height}
                        // stroke="#A9650E"
                        stroke={item.data?.color}
                        fillOpacity={'0'}
                    />
                    <text
                        className="text-[10px]"
                        x="6"
                        y="18"
                        fill={item.data?.color}
                    >
                        {item.data?.placeholder || 'Text'}
                    </text>
                </>
            )}

            {item.selected && (
                <RubberBand
                    item={item}
                    onResize={onResize}
                    onResized={onResized}
                    checkBox={item?.data?.type === FieldsTypeEnum.Checkbox}
                />
            )}
        </g>
    )
}
