import { UserRoles } from '@constants'
import { MdEmail } from 'react-icons/md'
import { AiOutlineUser } from 'react-icons/ai'
import { MdOutlinePhone } from 'react-icons/md'
import { FaSignature } from 'react-icons/fa'
import { CiCalendarDate } from 'react-icons/ci'
import { IoCheckbox } from 'react-icons/io5'
import { IoRadioButtonOnOutline } from 'react-icons/io5'
import { MdArrowDropDownCircle } from 'react-icons/md'
import { CiText } from 'react-icons/ci'
import { GoNumber } from 'react-icons/go'
import { MdDriveFileRenameOutline } from 'react-icons/md'
import { IoMdCodeWorking } from 'react-icons/io'

const ColorPreset = {
    student: '#f59e0b',
    rto: '#3b82f6',
    industry: '#10b981',
    coordinator: '#77757F',
    standard: '',
}

export enum FieldsTypeEnum {
    Text = 'text',
    Email = 'email',
    Date = 'date',
    Signature = 'signature',
    Checkbox = 'checkbox',
    Radio = 'radio',
    Phone = 'phone',
    Dropdown = 'dropdown',
}
export const SideBarFieldsData = {
    'Student Fields': [
        {
            text: 'Student Id',
            id: 'input-student-id',
            color: ColorPreset.student,
            placeholder: 'Student Id',
            preDefined: true,
            type: FieldsTypeEnum.Text,
            column: 'studentId',
            role: UserRoles.STUDENT,
            Icon: MdDriveFileRenameOutline,
        },
        {
            text: 'Student Name',
            id: 'input-student-name',
            color: ColorPreset.student,
            placeholder: 'Student Name',
            preDefined: true,
            type: FieldsTypeEnum.Text,
            column: 'name',
            Icon: AiOutlineUser,
            role: UserRoles.STUDENT,
        },
        {
            text: 'Student Email',
            id: 'input-student-email',
            color: ColorPreset.student,
            placeholder: 'Student Email',
            preDefined: true,
            type: FieldsTypeEnum.Email,
            column: 'email',
            Icon: MdEmail,
            role: UserRoles.STUDENT,
        },
        {
            text: 'Student Phone',
            id: 'input-student-phone',
            color: ColorPreset.student,
            placeholder: 'Student Phone',
            preDefined: true,
            type: FieldsTypeEnum.Text,
            column: 'phone',
            Icon: MdOutlinePhone,
            role: UserRoles.STUDENT,
        },
        {
            text: 'Student Sign Date',
            id: 'input-sign-student-date',
            color: ColorPreset.student,
            placeholder: 'Student Sign Date',
            preDefined: true,
            type: FieldsTypeEnum.Date,
            Icon: CiCalendarDate,
            column: 'date',
            role: UserRoles.STUDENT,
        },
        {
            text: 'Student Signature',
            id: 'input-student-signature',
            color: ColorPreset.student,
            placeholder: 'Student Signature',
            preDefined: true,
            type: FieldsTypeEnum.Signature,
            Icon: FaSignature,
            column: FieldsTypeEnum.Signature,
            role: UserRoles.STUDENT,
        },
    ],
    'RTO Fields': [
        {
            text: 'RTO Name',
            id: 'input-rto-name',
            color: ColorPreset.rto,
            placeholder: 'RTO Name',
            preDefined: true,
            type: FieldsTypeEnum.Text,
            column: 'name',
            Icon: AiOutlineUser,
            role: UserRoles.RTO,
        },
        {
            text: 'RTO Email',
            id: 'input-rto-email',
            color: ColorPreset.rto,
            placeholder: 'RTO Email',
            preDefined: true,
            type: FieldsTypeEnum.Email,
            column: 'email',
            Icon: MdEmail,
            role: UserRoles.RTO,
        },
        {
            text: 'RTO Code',
            id: 'input-rto-code',
            color: ColorPreset.rto,
            placeholder: 'RTO Code',
            preDefined: true,
            type: FieldsTypeEnum.Text,
            column: 'rtoCode',
            role: UserRoles.RTO,
            Icon: IoMdCodeWorking,
        },
        {
            text: 'RTO Phone',
            id: 'input-rto-phone',
            color: ColorPreset.rto,
            placeholder: 'RTO Phone',
            preDefined: true,
            type: FieldsTypeEnum.Text,
            column: 'phone',
            Icon: MdOutlinePhone,
            role: UserRoles.RTO,
        },
        {
            text: 'RTO Sign Date',
            id: 'input-rto-sign-date',
            color: ColorPreset.rto,
            placeholder: 'RTO Sign Date',
            preDefined: true,
            type: FieldsTypeEnum.Date,
            Icon: CiCalendarDate,
            column: 'date',
            role: UserRoles.RTO,
        },
        {
            text: 'RTO Signature',
            id: 'input-rto-signature',
            color: ColorPreset.rto,
            placeholder: 'RTO Signature',
            preDefined: true,
            type: FieldsTypeEnum.Signature,
            Icon: FaSignature,
            column: 'signature',
            role: UserRoles.RTO,
        },
    ],
    'Industry Fields': [
        {
            text: 'Industry Name',
            id: 'input-industry-name',
            color: ColorPreset.industry,
            placeholder: 'Industry Name',
            preDefined: true,
            type: FieldsTypeEnum.Text,
            column: 'name',
            Icon: AiOutlineUser,
            role: UserRoles.INDUSTRY,
        },
        {
            text: 'Industry Email',
            id: 'input-industry-email',
            color: ColorPreset.industry,
            placeholder: 'Industry Email',
            preDefined: true,
            type: FieldsTypeEnum.Email,
            column: 'email',
            Icon: MdEmail,
            role: UserRoles.INDUSTRY,
        },
        {
            text: 'Industry ABN',
            id: 'input-industry-abn',
            color: ColorPreset.industry,
            placeholder: 'Industry ABN',
            preDefined: true,
            type: FieldsTypeEnum.Text,
            column: 'abn',
            role: UserRoles.INDUSTRY,
            Icon: GoNumber,
        },
        {
            text: 'Industry Phone',
            id: 'input-industry-phone',
            color: ColorPreset.industry,
            placeholder: 'Industry Phone',
            preDefined: true,
            type: FieldsTypeEnum.Text,
            column: 'phoneNumber',
            Icon: MdOutlinePhone,
            role: UserRoles.INDUSTRY,
        },
        {
            text: 'Industry Sign Date',
            id: 'input-industry-sign-date',
            color: ColorPreset.industry,
            placeholder: 'Industry Sign Date',
            preDefined: true,
            type: FieldsTypeEnum.Date,
            Icon: CiCalendarDate,
            column: 'date',
            role: UserRoles.INDUSTRY,
        },
        {
            text: 'Industry Signature',
            id: 'input-industry-signature',
            color: ColorPreset.industry,
            placeholder: 'Industry Signature',
            preDefined: true,
            type: FieldsTypeEnum.Signature,
            Icon: FaSignature,
            column: 'signature',
            role: UserRoles.INDUSTRY,
        },
    ],
    'Coordinator Fields': [
        {
            text: 'Coordinator Name',
            id: 'input-coordinator-name',
            color: ColorPreset.coordinator,
            placeholder: 'Coordinator Name',
            preDefined: true,
            type: FieldsTypeEnum.Text,
            column: 'name',
            Icon: AiOutlineUser,
            role: UserRoles.SUBADMIN,
        },
        {
            text: 'Coordinator Email',
            id: 'input-coordinator-email',
            color: ColorPreset.coordinator,
            placeholder: 'Coordinator Email',
            preDefined: true,
            type: FieldsTypeEnum.Email,
            column: 'email',
            Icon: MdEmail,
            role: UserRoles.SUBADMIN,
        },
        {
            text: 'Coordinator Phone',
            id: 'input-coordinator-phone',
            color: ColorPreset.coordinator,
            placeholder: 'Coordinator Phone',
            preDefined: true,
            type: FieldsTypeEnum.Text,
            column: 'phone',
            Icon: MdOutlinePhone,
            role: UserRoles.SUBADMIN,
        },
        {
            text: 'Subadmin Sign Date',
            id: 'input-subadmin-sign-date',
            color: ColorPreset.coordinator,
            placeholder: 'Subadmin Sign Date',
            preDefined: true,
            type: FieldsTypeEnum.Date,
            Icon: CiCalendarDate,
            column: 'date',
            role: UserRoles.SUBADMIN,
        },
        {
            text: 'Coordinator Signature',
            id: 'input-coordinator-signature',
            color: ColorPreset.coordinator,
            placeholder: 'Coordinator Signature',
            preDefined: true,
            type: FieldsTypeEnum.Signature,
            Icon: FaSignature,
            column: 'signature',
            role: UserRoles.SUBADMIN,
        },
    ],
    'Standard Fields': [
        {
            text: 'Text Field',
            id: 'text',
            color: ColorPreset.industry,
            placeholder: 'Text Field',
            type: FieldsTypeEnum.Text,
            column: 'custom',
            isCustom: true,
            name: '',
            Icon: CiText,
        },
        {
            text: 'CheckBox',
            id: 'checkbox',
            color: ColorPreset.industry,
            placeholder: 'CheckBox',
            type: FieldsTypeEnum.Checkbox,
            isCustom: true,
            column: 'custom',
            name: '',
            Icon: IoCheckbox,
        },
        // {
        //     text: 'Radio Button',
        //     id: 'radioButton',
        //     color: ColorPreset.industry,
        //     placeholder: 'Radio Button',
        //     type: FieldsTypeEnum.Radio,
        //     isCustom: true,
        //     column: 'custom',
        //     name: '',
        //     Icon: IoRadioButtonOnOutline,
        // },
        {
            text: 'Dropdown',
            id: 'dropdown',
            color: ColorPreset.industry,
            placeholder: 'Dropdown',
            isCustom: true,
            column: 'custom',
            type: FieldsTypeEnum.Dropdown,
            name: '',
            Icon: MdArrowDropDownCircle,
        },
    ],
}
